-- P0.5b-v2 / B5 (docs/_TODO/SAAS_FOUNDATION/LOG.md, taskdb #655): dormant table-level GRANTs
-- for the fixed app_staff / app_patient roles created by
-- deploy/postgres/p0-5b-role-split-staff-patient.sql.
--
-- Generated by docs/_TODO/SAAS_FOUNDATION/scripts/p0-5b-grants-sql.mjs.
-- Do not edit the generated grant lists by hand; update the generator and regenerate. See that
-- script's header + docs/_TODO/SAAS_FOUNDATION/P0_5B_GRANTS.md for the full rationale (why each
-- table got SELECT-only vs a write grant, and which BOOTSTRAP tables were deliberately excluded).
--
-- Purpose:
--   - app_staff: the reviewed P0.5b runtime DML surface (SCOPED +
--     BOOTSTRAP + INFRA + LEGACY + TELEMETRY, excluding migration bookkeeping and post-P0.5b tables
--     whose dedicated overlays own their grants).
--   - app_patient: ONLY the patient-facing surface (the patient-owned
--     SCOPED set + a small confirmed BOOTSTRAP identity/settings subset). SELECT by default;
--     INSERT/UPDATE/DELETE added only where a patient-authenticated route/repo confirms the write.
--
-- Dormant boundary (same as p0-5b-role-split-staff-patient.sql):
--   - this script does not change application DATABASE_URL values or switch any runtime process to
--     either role;
--   - this script does not deploy, migrate, or enable new RLS enforcement;
--   - this script ONLY adds GRANTs to the two already-existing (dormant, no-credential) roles.
--
-- Requires app_staff/app_patient to already exist -- run p0-5b-role-split-staff-patient.sql first.
--
-- No psql variables required (role names are fixed) -- invoke directly:
--   psql '<database-url>' -f deploy/postgres/p0-5b-grants.sql
--
-- Rollback:
--   Re-run with -v p0_5b_grants_down=1. Revokes ALL privileges this script could have granted from
--   both roles (REVOKE ALL is idempotent/safe even for a privilege subset). Does not drop the roles
--   themselves -- that remains p0-5b-role-split-staff-patient.sql's job.

\set ON_ERROR_STOP on
\pset pager off

SELECT (
  EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_staff')
  AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_patient')
)::int AS p0_5b_grants_roles_exist \gset

\if :p0_5b_grants_roles_exist
\else
\echo 'FATAL: app_staff/app_patient must already exist -- run p0-5b-role-split-staff-patient.sql first.'
SELECT 1 / 0 AS p0_5b_grants_abort;
\endif

CREATE TEMP TABLE p0_5b_staff_grant_tables (
  schema_name name NOT NULL,
  table_name name NOT NULL,
  PRIMARY KEY (schema_name, table_name)
);
-- Session-scoped TEMP table (NOT ON COMMIT DROP -- psql autocommit; see p0-5-role-split.sql's note
-- of the same shape, found live 2026-07-11).

INSERT INTO p0_5b_staff_grant_tables (schema_name, table_name)
VALUES
  ('integrator', 'contacts'),
  ('integrator', 'content_access_grants'),
  ('integrator', 'conversation_messages'),
  ('integrator', 'conversations'),
  ('integrator', 'delivery_attempt_logs'),
  ('integrator', 'idempotency_keys'),
  ('integrator', 'identities'),
  ('integrator', 'integration_data_quality_incidents'),
  ('integrator', 'message_drafts'),
  ('integrator', 'message_retry_jobs'),
  ('integrator', 'projection_outbox'),
  ('integrator', 'question_messages'),
  ('integrator', 'telegram_state'),
  ('integrator', 'telegram_users'),
  ('integrator', 'user_questions'),
  ('integrator', 'user_reminder_delivery_logs'),
  ('integrator', 'user_reminder_occurrences'),
  ('integrator', 'users'),
  ('public', 'admin_audit_log'),
  ('public', 'appointment_records'),
  ('public', 'auth_rate_limit_events'),
  ('public', 'be_appointment_cancellations'),
  ('public', 'be_appointment_events'),
  ('public', 'be_appointment_history_events'),
  ('public', 'be_appointment_no_shows'),
  ('public', 'be_appointment_reschedules'),
  ('public', 'be_appointment_staff_comments'),
  ('public', 'be_appointments'),
  ('public', 'be_availability_rules'),
  ('public', 'be_booking_form_fields'),
  ('public', 'be_booking_form_submissions'),
  ('public', 'be_branches'),
  ('public', 'be_cancellation_policies'),
  ('public', 'be_clinic_services'),
  ('public', 'be_external_entity_mappings'),
  ('public', 'be_organization_members'),
  ('public', 'be_organizations'),
  ('public', 'be_package_history_events'),
  ('public', 'be_package_items'),
  ('public', 'be_package_usages'),
  ('public', 'be_patient_booking_profiles'),
  ('public', 'be_patient_package_items'),
  ('public', 'be_patient_packages'),
  ('public', 'be_patient_timeline_events'),
  ('public', 'be_payment_history_events'),
  ('public', 'be_payment_intents'),
  ('public', 'be_payment_provider_events'),
  ('public', 'be_payments'),
  ('public', 'be_prepayment_policies'),
  ('public', 'be_refunds'),
  ('public', 'be_reschedule_policies'),
  ('public', 'be_rooms'),
  ('public', 'be_schedule_blocks'),
  ('public', 'be_schedule_templates'),
  ('public', 'be_service_location_availability'),
  ('public', 'be_specialist_locations'),
  ('public', 'be_specialist_rooms'),
  ('public', 'be_specialist_service_availability'),
  ('public', 'be_specialists'),
  ('public', 'be_subscription_packages'),
  ('public', 'be_working_days'),
  ('public', 'be_working_hours'),
  ('public', 'booking_cities'),
  ('public', 'broadcast_audit'),
  ('public', 'broadcast_audit_recipients'),
  ('public', 'broadcast_drafts'),
  ('public', 'channel_link_secrets'),
  ('public', 'clinic_public_directory_entries'),
  ('public', 'clinical_anamnesis_illness'),
  ('public', 'clinical_anamnesis_lifestyle'),
  ('public', 'clinical_anamnesis_trauma'),
  ('public', 'clinical_complaint'),
  ('public', 'clinical_complaint_update'),
  ('public', 'clinical_diagnosis'),
  ('public', 'clinical_diagnosis_catalog'),
  ('public', 'clinical_diagnosis_status_history'),
  ('public', 'clinical_diagnosis_update'),
  ('public', 'clinical_test_measure_kinds'),
  ('public', 'clinical_test_regions'),
  ('public', 'clinical_visit'),
  ('public', 'comments'),
  ('public', 'content_access_grants_webapp'),
  ('public', 'content_pages'),
  ('public', 'content_section_slug_history'),
  ('public', 'content_sections'),
  ('public', 'courses'),
  ('public', 'doctor_notes'),
  ('public', 'doctor_patient_support'),
  ('public', 'email_challenges'),
  ('public', 'email_otp_locks'),
  ('public', 'email_send_cooldowns'),
  ('public', 'idempotency_keys'),
  ('public', 'integration_webhook_error_events'),
  ('public', 'integration_webhook_last_status'),
  ('public', 'integrator_push_outbox'),
  ('public', 'lfk_complex_exercises'),
  ('public', 'lfk_complex_template_exercises'),
  ('public', 'lfk_complex_templates'),
  ('public', 'lfk_complexes'),
  ('public', 'lfk_exercise_media'),
  ('public', 'lfk_exercise_regions'),
  ('public', 'lfk_exercises'),
  ('public', 'lfk_sessions'),
  ('public', 'login_tokens'),
  ('public', 'material_ratings'),
  ('public', 'media_files'),
  ('public', 'media_folders'),
  ('public', 'media_hls_proxy_error_events'),
  ('public', 'media_playback_client_events'),
  ('public', 'media_playback_resolution_events'),
  ('public', 'media_playback_stats_hourly'),
  ('public', 'media_playback_user_video_first_resolve'),
  ('public', 'media_transcode_jobs'),
  ('public', 'media_upload_sessions'),
  ('public', 'message_log'),
  ('public', 'motivational_quotes'),
  ('public', 'notification_delivery_attempts'),
  ('public', 'online_intake_answers'),
  ('public', 'online_intake_attachments'),
  ('public', 'online_intake_requests'),
  ('public', 'online_intake_status_history'),
  ('public', 'operator_health_alert_sent'),
  ('public', 'operator_health_failure_archive'),
  ('public', 'operator_incidents'),
  ('public', 'operator_job_status'),
  ('public', 'org_enrollments'),
  ('public', 'outgoing_delivery_queue'),
  ('public', 'patient_bookings'),
  ('public', 'patient_comorbidity'),
  ('public', 'patient_content_rating_feedback'),
  ('public', 'patient_daily_warmup_presentations'),
  ('public', 'patient_daily_warmup_video_views'),
  ('public', 'patient_diary_day_snapshots'),
  ('public', 'patient_files'),
  ('public', 'patient_home_block_items'),
  ('public', 'patient_home_blocks'),
  ('public', 'patient_lfk_assignments'),
  ('public', 'patient_merge_candidates'),
  ('public', 'patient_payment'),
  ('public', 'patient_practice_completions'),
  ('public', 'phone_challenges'),
  ('public', 'phone_messenger_bind_secrets'),
  ('public', 'phone_otp_locks'),
  ('public', 'platform_user_contacts'),
  ('public', 'platform_users'),
  ('public', 'product_analytics_events_recent'),
  ('public', 'product_analytics_hourly'),
  ('public', 'product_analytics_user_hourly'),
  ('public', 'product_push_notifications'),
  ('public', 'program_action_log'),
  ('public', 'program_item_discussion_messages'),
  ('public', 'program_item_discussion_reads'),
  ('public', 'recommendation_regions'),
  ('public', 'recommendations'),
  ('public', 'reference_categories'),
  ('public', 'reference_items'),
  ('public', 'reminder_delivery_events'),
  ('public', 'reminder_journal'),
  ('public', 'reminder_occurrence_history'),
  ('public', 'reminder_rules'),
  ('public', 'specialist_tasks'),
  ('public', 'support_conversation_messages'),
  ('public', 'support_conversations'),
  ('public', 'support_delivery_events'),
  ('public', 'support_question_messages'),
  ('public', 'support_questions'),
  ('public', 'symptom_entries'),
  ('public', 'symptom_trackings'),
  ('public', 'system_settings'),
  ('public', 'system_settings_audit'),
  ('public', 'test_attempts'),
  ('public', 'test_results'),
  ('public', 'test_set_items'),
  ('public', 'test_sets'),
  ('public', 'tests'),
  ('public', 'treatment_program_events'),
  ('public', 'treatment_program_instance_stage_groups'),
  ('public', 'treatment_program_instance_stage_items'),
  ('public', 'treatment_program_instance_stages'),
  ('public', 'treatment_program_instances'),
  ('public', 'treatment_program_template_stage_groups'),
  ('public', 'treatment_program_template_stage_items'),
  ('public', 'treatment_program_template_stages'),
  ('public', 'treatment_program_templates'),
  ('public', 'user_channel_bindings'),
  ('public', 'user_channel_preferences'),
  ('public', 'user_email_setup_tokens'),
  ('public', 'user_notification_topic_channels'),
  ('public', 'user_notification_topics'),
  ('public', 'user_oauth_bindings'),
  ('public', 'user_password_credentials'),
  ('public', 'user_phone_history'),
  ('public', 'user_pins'),
  ('public', 'user_web_push_subscriptions'),
  ('public', 'webapp_reminder_occurrences');

CREATE TEMP TABLE p0_5b_patient_grant_tables (
  schema_name name NOT NULL,
  table_name name NOT NULL,
  privileges text NOT NULL,
  PRIMARY KEY (schema_name, table_name)
);

INSERT INTO p0_5b_patient_grant_tables (schema_name, table_name, privileges)
VALUES
  ('integrator', 'contacts', 'SELECT'),
  ('integrator', 'content_access_grants', 'SELECT'),
  ('integrator', 'conversation_messages', 'SELECT'),
  ('integrator', 'conversations', 'SELECT'),
  ('integrator', 'message_drafts', 'SELECT'),
  ('integrator', 'question_messages', 'SELECT'),
  ('integrator', 'user_questions', 'SELECT'),
  ('integrator', 'user_reminder_delivery_logs', 'SELECT'),
  ('integrator', 'user_reminder_occurrences', 'SELECT'),
  ('public', 'be_appointment_cancellations', 'SELECT, INSERT'),
  ('public', 'be_appointment_events', 'SELECT, INSERT'),
  ('public', 'be_appointment_history_events', 'SELECT, INSERT'),
  ('public', 'be_appointment_no_shows', 'SELECT'),
  ('public', 'be_appointment_reschedules', 'SELECT, INSERT'),
  ('public', 'be_appointment_staff_comments', 'SELECT'),
  ('public', 'be_appointments', 'SELECT'),
  ('public', 'be_booking_form_submissions', 'SELECT, INSERT'),
  ('public', 'be_package_history_events', 'SELECT'),
  ('public', 'be_package_usages', 'SELECT'),
  ('public', 'be_patient_booking_profiles', 'SELECT'),
  ('public', 'be_patient_package_items', 'SELECT'),
  ('public', 'be_patient_packages', 'SELECT'),
  ('public', 'be_patient_timeline_events', 'SELECT, INSERT'),
  ('public', 'be_payment_history_events', 'SELECT'),
  ('public', 'be_payment_intents', 'SELECT'),
  ('public', 'be_payments', 'SELECT'),
  ('public', 'be_refunds', 'SELECT'),
  ('public', 'broadcast_audit_recipients', 'SELECT'),
  ('public', 'clinical_anamnesis_illness', 'SELECT'),
  ('public', 'clinical_anamnesis_lifestyle', 'SELECT'),
  ('public', 'clinical_anamnesis_trauma', 'SELECT'),
  ('public', 'clinical_complaint', 'SELECT'),
  ('public', 'clinical_complaint_update', 'SELECT'),
  ('public', 'clinical_diagnosis', 'SELECT'),
  ('public', 'clinical_diagnosis_status_history', 'SELECT'),
  ('public', 'clinical_diagnosis_update', 'SELECT'),
  ('public', 'clinical_visit', 'SELECT'),
  ('public', 'comments', 'SELECT'),
  ('public', 'content_access_grants_webapp', 'SELECT'),
  ('public', 'doctor_notes', 'SELECT'),
  ('public', 'doctor_patient_support', 'SELECT'),
  ('public', 'lfk_complex_exercises', 'SELECT'),
  ('public', 'lfk_complexes', 'SELECT'),
  ('public', 'lfk_sessions', 'SELECT, INSERT, UPDATE'),
  ('public', 'material_ratings', 'SELECT, INSERT, UPDATE'),
  ('public', 'media_files', 'SELECT'),
  ('public', 'media_folders', 'SELECT'),
  ('public', 'media_hls_proxy_error_events', 'SELECT'),
  ('public', 'media_playback_client_events', 'SELECT'),
  ('public', 'media_playback_resolution_events', 'SELECT'),
  ('public', 'media_playback_user_video_first_resolve', 'SELECT'),
  ('public', 'media_transcode_jobs', 'SELECT'),
  ('public', 'media_upload_sessions', 'SELECT, INSERT'),
  ('public', 'message_log', 'SELECT'),
  ('public', 'notification_delivery_attempts', 'SELECT'),
  ('public', 'online_intake_answers', 'SELECT, INSERT'),
  ('public', 'online_intake_attachments', 'SELECT, INSERT'),
  ('public', 'online_intake_requests', 'SELECT'),
  ('public', 'online_intake_status_history', 'SELECT'),
  ('public', 'org_enrollments', 'SELECT'),
  ('public', 'patient_comorbidity', 'SELECT'),
  ('public', 'patient_content_rating_feedback', 'SELECT, INSERT, UPDATE'),
  ('public', 'patient_daily_warmup_presentations', 'SELECT, INSERT'),
  ('public', 'patient_daily_warmup_video_views', 'SELECT, INSERT'),
  ('public', 'patient_diary_day_snapshots', 'SELECT, INSERT'),
  ('public', 'patient_files', 'SELECT'),
  ('public', 'patient_lfk_assignments', 'SELECT'),
  ('public', 'patient_payment', 'SELECT'),
  ('public', 'patient_practice_completions', 'SELECT, INSERT'),
  ('public', 'platform_user_contacts', 'SELECT'),
  ('public', 'platform_users', 'SELECT'),
  ('public', 'product_analytics_user_hourly', 'SELECT'),
  ('public', 'program_action_log', 'SELECT, INSERT'),
  ('public', 'program_item_discussion_messages', 'SELECT, INSERT'),
  ('public', 'program_item_discussion_reads', 'SELECT, INSERT, UPDATE'),
  ('public', 'reminder_delivery_events', 'SELECT'),
  ('public', 'reminder_journal', 'SELECT'),
  ('public', 'reminder_occurrence_history', 'SELECT'),
  ('public', 'reminder_rules', 'SELECT, INSERT, UPDATE'),
  ('public', 'support_conversation_messages', 'SELECT, INSERT'),
  ('public', 'support_conversations', 'SELECT'),
  ('public', 'support_delivery_events', 'SELECT'),
  ('public', 'support_question_messages', 'SELECT'),
  ('public', 'support_questions', 'SELECT'),
  ('public', 'symptom_entries', 'SELECT, INSERT, UPDATE'),
  ('public', 'symptom_trackings', 'SELECT, INSERT, UPDATE'),
  ('public', 'test_attempts', 'SELECT'),
  ('public', 'test_results', 'SELECT'),
  ('public', 'treatment_program_events', 'SELECT'),
  ('public', 'treatment_program_instance_stage_groups', 'SELECT'),
  ('public', 'treatment_program_instance_stage_items', 'SELECT'),
  ('public', 'treatment_program_instance_stages', 'SELECT'),
  ('public', 'treatment_program_instances', 'SELECT'),
  ('public', 'user_channel_bindings', 'SELECT'),
  ('public', 'user_channel_preferences', 'SELECT'),
  ('public', 'user_notification_topic_channels', 'SELECT, INSERT, UPDATE'),
  ('public', 'user_notification_topics', 'SELECT, INSERT, UPDATE'),
  ('public', 'user_oauth_bindings', 'SELECT'),
  ('public', 'user_phone_history', 'SELECT'),
  ('public', 'user_pins', 'SELECT, INSERT'),
  ('public', 'user_web_push_subscriptions', 'SELECT, INSERT, UPDATE, DELETE'),
  ('public', 'webapp_reminder_occurrences', 'SELECT');

\if :{?p0_5b_grants_down}
\echo 'P0.5b grants DOWN: revoking app_staff/app_patient table+sequence+schema grants.'

SELECT format('REVOKE ALL PRIVILEGES ON TABLE %I.%I FROM app_staff', schema_name, table_name)
FROM p0_5b_staff_grant_tables
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_staff')
ORDER BY schema_name, table_name
\gexec

SELECT format('REVOKE ALL PRIVILEGES ON TABLE %I.%I FROM app_patient', schema_name, table_name)
FROM p0_5b_patient_grant_tables
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_patient')
ORDER BY schema_name, table_name
\gexec

REVOKE ALL PRIVILEGES ON TABLE public.app_runtime_settings, public.app_runtime_settings_audit FROM app_staff;
REVOKE ALL PRIVILEGES ON TABLE public.app_runtime_settings FROM app_patient;

SELECT format('REVOKE USAGE, SELECT ON SEQUENCE %I.%I FROM app_staff', seq_ns.nspname, seq.relname)
FROM pg_class seq
JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype = 'a'
JOIN pg_class tbl ON tbl.oid = dep.refobjid
JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
JOIN p0_5b_staff_grant_tables targets ON targets.schema_name = tbl_ns.nspname AND targets.table_name = tbl.relname
WHERE seq.relkind = 'S'
  AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_staff')
ORDER BY seq_ns.nspname, seq.relname
\gexec

SELECT format('REVOKE USAGE, SELECT ON SEQUENCE %I.%I FROM app_patient', seq_ns.nspname, seq.relname)
FROM pg_class seq
JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype = 'a'
JOIN pg_class tbl ON tbl.oid = dep.refobjid
JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
JOIN p0_5b_patient_grant_tables targets ON targets.schema_name = tbl_ns.nspname AND targets.table_name = tbl.relname
WHERE seq.relkind = 'S'
  AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_patient')
ORDER BY seq_ns.nspname, seq.relname
\gexec

SELECT format('REVOKE USAGE ON SCHEMA %I FROM app_staff', 'integrator') WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_staff') \gexec
SELECT format('REVOKE USAGE ON SCHEMA %I FROM app_staff', 'public') WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_staff') \gexec

SELECT format('REVOKE USAGE ON SCHEMA %I FROM app_patient', 'integrator') WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_patient') \gexec
SELECT format('REVOKE USAGE ON SCHEMA %I FROM app_patient', 'public') WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_patient') \gexec

\echo 'P0.5b grants DOWN complete.'
\else
\echo 'P0.5b grants UP: app_staff full runtime surface, app_patient curated patient-facing surface.'

GRANT USAGE ON SCHEMA "integrator" TO app_staff;
GRANT USAGE ON SCHEMA "public" TO app_staff;
GRANT USAGE ON SCHEMA "integrator" TO app_patient;
GRANT USAGE ON SCHEMA "public" TO app_patient;

SELECT format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I.%I TO app_staff', schema_name, table_name)
FROM p0_5b_staff_grant_tables
ORDER BY schema_name, table_name
\gexec

SELECT format('GRANT %s ON TABLE %I.%I TO app_patient', privileges, schema_name, table_name)
FROM p0_5b_patient_grant_tables
ORDER BY schema_name, table_name
\gexec

-- Column-level GRANTs for app_patient, layered on top of the whole-table grants above. RLS
-- restricts ROWS, never COLUMNS -- see appPatientColumnGrants in the generator + P0_5B_GRANTS.md
-- "Column-level restrictions (app_patient)" for the table-by-table rationale (2026-07-11 gpt-5.6-sol
-- audit fix, taskdb #655).
GRANT UPDATE ("calendar_timezone", "reminder_muted_until") ON TABLE "public"."platform_users" TO app_patient;
GRANT UPDATE ("pin_hash") ON TABLE "public"."user_pins" TO app_patient;
GRANT INSERT ("organization_id", "branch_id", "room_id", "specialist_id", "service_id", "platform_user_id", "start_at", "end_at", "duration_minutes", "source", "status", "original_start_at", "reschedule_count", "phone_normalized", "attribution_json", "created_at", "updated_at") ON TABLE "public"."be_appointments" TO app_patient;
GRANT UPDATE ("status", "updated_at", "start_at", "end_at", "duration_minutes", "branch_id", "room_id", "specialist_id", "service_id", "original_start_at", "reschedule_count") ON TABLE "public"."be_appointments" TO app_patient;
GRANT UPDATE ("value_text") ON TABLE "public"."be_booking_form_submissions" TO app_patient;
GRANT UPDATE ("notifications_sent") ON TABLE "public"."be_appointment_cancellations" TO app_patient;
GRANT UPDATE ("notifications_sent") ON TABLE "public"."be_appointment_reschedules" TO app_patient;
GRANT INSERT ("organization_id", "integrator_conversation_id", "platform_user_id", "integrator_user_id", "source", "admin_scope", "status", "opened_at", "last_message_at") ON TABLE "public"."support_conversations" TO app_patient;
GRANT UPDATE ("organization_id", "platform_user_id", "updated_at") ON TABLE "public"."support_conversations" TO app_patient;
GRANT INSERT ("id", "original_name", "stored_path", "s3_key", "mime_type", "size_bytes", "uploaded_by", "folder_id", "usage_purpose", "video_delivery_override") ON TABLE "public"."media_files" TO app_patient;
GRANT UPDATE ("status") ON TABLE "public"."media_files" TO app_patient;
GRANT UPDATE ("status", "completed_at", "last_error", "updated_at") ON TABLE "public"."media_upload_sessions" TO app_patient;
GRANT UPDATE ("local_comment") ON TABLE "public"."lfk_complex_exercises" TO app_patient;
GRANT INSERT ("organization_id", "instance_stage_item_id", "patient_user_id") ON TABLE "public"."test_attempts" TO app_patient;
GRANT UPDATE ("submitted_at") ON TABLE "public"."test_attempts" TO app_patient;
GRANT INSERT ("user_id", "platform_user_id", "title", "is_active", "updated_at", "symptom_tracking_id", "region_ref_id", "side", "diagnosis_text", "diagnosis_ref_id") ON TABLE "public"."lfk_complexes" TO app_patient;
GRANT INSERT ("organization_id", "instance_id", "event_type", "target_type", "target_id", "payload", "reason") ON TABLE "public"."treatment_program_events" TO app_patient;
GRANT INSERT ("id", "user_id", "organization_id", "type", "summary") ON TABLE "public"."online_intake_requests" TO app_patient;
GRANT INSERT ("id", "request_id", "organization_id", "from_status", "to_status") ON TABLE "public"."online_intake_status_history" TO app_patient;
GRANT INSERT ("user_id", "platform_user_id", "channel_code", "is_enabled_for_messages", "is_enabled_for_notifications", "is_preferred_for_auth", "updated_at") ON TABLE "public"."user_channel_preferences" TO app_patient;
GRANT UPDATE ("platform_user_id", "is_enabled_for_messages", "is_enabled_for_notifications", "is_preferred_for_auth", "updated_at") ON TABLE "public"."user_channel_preferences" TO app_patient;

-- Safety REVOKEs for sensitive BOOTSTRAP tables deliberately excluded from the app_patient surface.
-- These make the UP path idempotently repair stale over-grants from earlier rehearsals.
-- U3S: staff MFA secrets, recovery hashes and login challenges stay table-invisible to app_patient; runtime access is only through self-scoped SECURITY DEFINER functions.
REVOKE ALL PRIVILEGES ON TABLE "public"."staff_security_profiles" FROM app_patient;
SELECT format(
  'REVOKE ALL PRIVILEGES (%s) ON TABLE %I.%I FROM app_patient',
  string_agg(quote_ident(attname), ', ' ORDER BY attnum),
  'public',
  'staff_security_profiles'
)
FROM pg_attribute
WHERE attrelid = 'public.staff_security_profiles'::regclass
  AND attnum > 0
  AND NOT attisdropped
\gexec

-- D3.5: password hashes stay table-invisible to app_patient; patient code uses app.current_patient_has_password_credentials() for boolean presence only.
REVOKE ALL PRIVILEGES ON TABLE "public"."user_password_credentials" FROM app_patient;
SELECT format(
  'REVOKE ALL PRIVILEGES (%s) ON TABLE %I.%I FROM app_patient',
  string_agg(quote_ident(attname), ', ' ORDER BY attnum),
  'public',
  'user_password_credentials'
)
FROM pg_attribute
WHERE attrelid = 'public.user_password_credentials'::regclass
  AND attnum > 0
  AND NOT attisdropped
\gexec

-- D3.5: OAuth bindings stay table-invisible to app_patient; patient code uses app.current_patient_has_web_oauth_binding() for boolean presence only.
REVOKE ALL PRIVILEGES ON TABLE "public"."user_oauth_bindings" FROM app_patient;
SELECT format(
  'REVOKE ALL PRIVILEGES (%s) ON TABLE %I.%I FROM app_patient',
  string_agg(quote_ident(attname), ', ' ORDER BY attnum),
  'public',
  'user_oauth_bindings'
)
FROM pg_attribute
WHERE attrelid = 'public.user_oauth_bindings'::regclass
  AND attnum > 0
  AND NOT attisdropped
\gexec

-- S5-2: the safe runtime store is directly readable by app_patient, while every
-- restricted/audit surface stays physically unavailable. Re-running the UP path repairs stale ACLs.
REVOKE ALL PRIVILEGES ON TABLE
  public.system_settings,
  public.system_settings_audit,
  public.app_runtime_settings_audit
  FROM PUBLIC, app_patient;
GRANT SELECT ON TABLE public.app_runtime_settings TO app_patient;
-- Normalize before the narrow grants so a repeat run removes stale audit UPDATE/DELETE.
REVOKE ALL PRIVILEGES ON TABLE
  public.app_runtime_settings,
  public.app_runtime_settings_audit
  FROM app_staff;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.app_runtime_settings TO app_staff;
GRANT SELECT, INSERT ON TABLE public.app_runtime_settings_audit TO app_staff;
DO $s5_bootstrap_acl$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_runtime_nonstaff_login') THEN
    REVOKE ALL PRIVILEGES ON TABLE public.system_settings FROM app_runtime_nonstaff_login;
    REVOKE ALL PRIVILEGES ON TABLE public.system_settings_audit FROM app_runtime_nonstaff_login;
    REVOKE ALL PRIVILEGES ON TABLE public.app_runtime_settings_audit FROM app_runtime_nonstaff_login;
  END IF;
END
$s5_bootstrap_acl$;

SELECT format('GRANT USAGE, SELECT ON SEQUENCE %I.%I TO app_staff', seq_ns.nspname, seq.relname)
FROM pg_class seq
JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype = 'a'
JOIN pg_class tbl ON tbl.oid = dep.refobjid
JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
JOIN p0_5b_staff_grant_tables targets ON targets.schema_name = tbl_ns.nspname AND targets.table_name = tbl.relname
WHERE seq.relkind = 'S'
ORDER BY seq_ns.nspname, seq.relname
\gexec

SELECT format('GRANT USAGE, SELECT ON SEQUENCE %I.%I TO app_patient', seq_ns.nspname, seq.relname)
FROM pg_class seq
JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype = 'a'
JOIN pg_class tbl ON tbl.oid = dep.refobjid
JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
JOIN p0_5b_patient_grant_tables targets ON targets.schema_name = tbl_ns.nspname AND targets.table_name = tbl.relname
WHERE seq.relkind = 'S'
ORDER BY seq_ns.nspname, seq.relname
\gexec

-- Re-assert the B4-roles-1 security invariant: issuing a large batch of GRANTs here must not
-- accidentally create or reveal a membership path from app_patient to app_staff. Same pg_has_role
-- transitive check as p0-5b-role-split-staff-patient.sql and the p0-5-role-split.sql fix above.
SELECT (NOT pg_has_role('app_patient', 'app_staff', 'MEMBER'))::int AS p0_5b_grants_patient_not_staff_ok \gset

\if :p0_5b_grants_patient_not_staff_ok
\else
\echo 'FATAL: P0.5b grants -- app_patient must NOT be a member of app_staff (directly or transitively).'
SELECT 1 / 0 AS p0_5b_grants_abort;
\endif

\echo 'P0.5b grants UP complete.'
\endif
