-- P0.5 / B5 dormant DB role split.
-- Generated by docs/_TODO/SAAS_FOUNDATION/scripts/p0-5-role-split-sql.mjs.
-- Do not edit the generated grant list by hand; update the SaaS tier artifacts and regenerate.
--
-- Purpose:
--   - create/normalize an owner role and deploy-only migrator role with BYPASSRLS for DDL/backfills;
--   - create/normalize a non-owner application role with NOBYPASSRLS;
--   - grant the app role runtime DML on SCOPED and BOOTSTRAP tables only.
--
-- Dormant boundary:
--   - this script does not change application DATABASE_URL values;
--   - this script does not switch runtime processes to the app role;
--   - this script does not deploy, migrate, or enable new RLS enforcement.
--
-- Required psql variables:
--   - p0_5_owner_role
--   - p0_5_migrator_role
--   - p0_5_app_role
--
-- Example shape only, with operator-chosen role names:
--   psql '<database-url>' \
--     -v p0_5_owner_role='<owner_role>' \
--     -v p0_5_migrator_role='<migrator_role>' \
--     -v p0_5_app_role='<app_role>' \
--     -f deploy/postgres/p0-5-role-split.sql
--
-- Rollback:
--   Re-run with -v p0_5_down=1 and the same role variables. The down block revokes
--   grants/memberships and drops the roles only if PostgreSQL allows it. It intentionally
--   does not REASSIGN OWNED or DROP OWNED, because those are destructive ownership operations.

\set ON_ERROR_STOP on
\pset pager off

\if :{?p0_5_owner_role}
\else
\echo 'FATAL: missing required psql variable p0_5_owner_role.'
SELECT 1 / 0 AS p0_5_abort;
\endif

\if :{?p0_5_migrator_role}
\else
\echo 'FATAL: missing required psql variable p0_5_migrator_role.'
SELECT 1 / 0 AS p0_5_abort;
\endif

\if :{?p0_5_app_role}
\else
\echo 'FATAL: missing required psql variable p0_5_app_role.'
SELECT 1 / 0 AS p0_5_abort;
\endif

SELECT (
  length(:'p0_5_owner_role') > 0
  AND length(:'p0_5_migrator_role') > 0
  AND length(:'p0_5_app_role') > 0
  AND :'p0_5_owner_role' <> :'p0_5_migrator_role'
  AND :'p0_5_owner_role' <> :'p0_5_app_role'
  AND :'p0_5_migrator_role' <> :'p0_5_app_role'
)::int AS p0_5_role_names_valid \gset

\if :p0_5_role_names_valid
\else
\echo 'FATAL: P0.5 role names must be non-empty and distinct.'
SELECT 1 / 0 AS p0_5_abort;
\endif

SELECT rolsuper::int AS p0_5_can_manage_roles
FROM pg_roles
WHERE rolname = current_user \gset

\if :p0_5_can_manage_roles
\else
\echo 'FATAL: P0.5 role split requires a superuser-capable executor because owner/migrator roles use BYPASSRLS.'
SELECT 1 / 0 AS p0_5_abort;
\endif

CREATE TEMP TABLE p0_5_app_grant_tables (
  schema_name name NOT NULL,
  table_name name NOT NULL,
  tier text NOT NULL CHECK (tier IN ('SCOPED', 'BOOTSTRAP')),
  PRIMARY KEY (schema_name, table_name)
);
-- Session-scoped TEMP table (NOT ON COMMIT DROP): psql runs statements in autocommit, so
-- ON COMMIT DROP would drop the table immediately after CREATE, before the INSERT. It is
-- auto-dropped when the psql session ends. (Found by live scratch proof, 2026-07-11.)

INSERT INTO p0_5_app_grant_tables (schema_name, table_name, tier)
VALUES
  ('integrator', 'contacts', 'SCOPED'),
  ('integrator', 'content_access_grants', 'SCOPED'),
  ('integrator', 'conversation_messages', 'SCOPED'),
  ('integrator', 'conversations', 'SCOPED'),
  ('integrator', 'identities', 'BOOTSTRAP'),
  ('integrator', 'message_drafts', 'SCOPED'),
  ('integrator', 'question_messages', 'SCOPED'),
  ('integrator', 'telegram_state', 'BOOTSTRAP'),
  ('integrator', 'telegram_users', 'BOOTSTRAP'),
  ('integrator', 'user_questions', 'SCOPED'),
  ('integrator', 'user_reminder_delivery_logs', 'SCOPED'),
  ('integrator', 'user_reminder_occurrences', 'SCOPED'),
  ('integrator', 'user_reminder_rules', 'SCOPED'),
  ('integrator', 'users', 'BOOTSTRAP'),
  ('public', 'admin_audit_log', 'SCOPED'),
  ('public', 'be_appointment_cancellations', 'SCOPED'),
  ('public', 'be_appointment_events', 'SCOPED'),
  ('public', 'be_appointment_history_events', 'SCOPED'),
  ('public', 'be_appointment_no_shows', 'SCOPED'),
  ('public', 'be_appointment_reschedules', 'SCOPED'),
  ('public', 'be_appointment_staff_comments', 'SCOPED'),
  ('public', 'be_appointments', 'SCOPED'),
  ('public', 'be_availability_rules', 'SCOPED'),
  ('public', 'be_booking_form_fields', 'SCOPED'),
  ('public', 'be_booking_form_submissions', 'SCOPED'),
  ('public', 'be_branches', 'SCOPED'),
  ('public', 'be_cancellation_policies', 'SCOPED'),
  ('public', 'be_clinic_services', 'SCOPED'),
  ('public', 'be_external_entity_mappings', 'SCOPED'),
  ('public', 'be_organization_members', 'BOOTSTRAP'),
  ('public', 'be_organizations', 'SCOPED'),
  ('public', 'be_package_history_events', 'SCOPED'),
  ('public', 'be_package_items', 'SCOPED'),
  ('public', 'be_package_usages', 'SCOPED'),
  ('public', 'be_patient_booking_profiles', 'SCOPED'),
  ('public', 'be_patient_package_items', 'SCOPED'),
  ('public', 'be_patient_packages', 'SCOPED'),
  ('public', 'be_patient_timeline_events', 'SCOPED'),
  ('public', 'be_payment_history_events', 'SCOPED'),
  ('public', 'be_payment_intents', 'SCOPED'),
  ('public', 'be_payment_provider_events', 'SCOPED'),
  ('public', 'be_payments', 'SCOPED'),
  ('public', 'be_prepayment_policies', 'SCOPED'),
  ('public', 'be_refunds', 'SCOPED'),
  ('public', 'be_reschedule_policies', 'SCOPED'),
  ('public', 'be_rooms', 'SCOPED'),
  ('public', 'be_schedule_blocks', 'SCOPED'),
  ('public', 'be_schedule_templates', 'SCOPED'),
  ('public', 'be_service_location_availability', 'SCOPED'),
  ('public', 'be_specialist_locations', 'SCOPED'),
  ('public', 'be_specialist_rooms', 'SCOPED'),
  ('public', 'be_specialist_service_availability', 'SCOPED'),
  ('public', 'be_specialists', 'SCOPED'),
  ('public', 'be_subscription_packages', 'SCOPED'),
  ('public', 'be_working_days', 'SCOPED'),
  ('public', 'be_working_hours', 'SCOPED'),
  ('public', 'broadcast_audit', 'SCOPED'),
  ('public', 'broadcast_audit_recipients', 'SCOPED'),
  ('public', 'broadcast_drafts', 'SCOPED'),
  ('public', 'channel_link_secrets', 'BOOTSTRAP'),
  ('public', 'clinic_public_directory_entries', 'SCOPED'),
  ('public', 'clinical_anamnesis_illness', 'SCOPED'),
  ('public', 'clinical_anamnesis_lifestyle', 'SCOPED'),
  ('public', 'clinical_anamnesis_trauma', 'SCOPED'),
  ('public', 'clinical_complaint', 'SCOPED'),
  ('public', 'clinical_complaint_update', 'SCOPED'),
  ('public', 'clinical_diagnosis', 'SCOPED'),
  ('public', 'clinical_diagnosis_catalog', 'SCOPED'),
  ('public', 'clinical_diagnosis_status_history', 'SCOPED'),
  ('public', 'clinical_diagnosis_update', 'SCOPED'),
  ('public', 'clinical_test_regions', 'SCOPED'),
  ('public', 'clinical_visit', 'SCOPED'),
  ('public', 'comments', 'SCOPED'),
  ('public', 'content_access_grants_webapp', 'SCOPED'),
  ('public', 'content_pages', 'SCOPED'),
  ('public', 'content_section_slug_history', 'SCOPED'),
  ('public', 'content_sections', 'SCOPED'),
  ('public', 'courses', 'SCOPED'),
  ('public', 'doctor_notes', 'SCOPED'),
  ('public', 'doctor_patient_support', 'SCOPED'),
  ('public', 'email_challenges', 'BOOTSTRAP'),
  ('public', 'email_send_cooldowns', 'BOOTSTRAP'),
  ('public', 'lfk_complex_exercises', 'SCOPED'),
  ('public', 'lfk_complex_template_exercises', 'SCOPED'),
  ('public', 'lfk_complex_templates', 'SCOPED'),
  ('public', 'lfk_complexes', 'SCOPED'),
  ('public', 'lfk_exercise_media', 'SCOPED'),
  ('public', 'lfk_exercise_regions', 'SCOPED'),
  ('public', 'lfk_exercises', 'SCOPED'),
  ('public', 'lfk_sessions', 'SCOPED'),
  ('public', 'login_tokens', 'BOOTSTRAP'),
  ('public', 'material_ratings', 'SCOPED'),
  ('public', 'media_files', 'SCOPED'),
  ('public', 'media_folders', 'SCOPED'),
  ('public', 'media_hls_proxy_error_events', 'SCOPED'),
  ('public', 'media_playback_client_events', 'SCOPED'),
  ('public', 'media_playback_resolution_events', 'SCOPED'),
  ('public', 'media_playback_user_video_first_resolve', 'SCOPED'),
  ('public', 'media_transcode_jobs', 'SCOPED'),
  ('public', 'media_upload_sessions', 'SCOPED'),
  ('public', 'message_log', 'SCOPED'),
  ('public', 'motivational_quotes', 'SCOPED'),
  ('public', 'notification_delivery_attempts', 'SCOPED'),
  ('public', 'online_intake_answers', 'SCOPED'),
  ('public', 'online_intake_attachments', 'SCOPED'),
  ('public', 'online_intake_requests', 'SCOPED'),
  ('public', 'online_intake_status_history', 'SCOPED'),
  ('public', 'operator_health_failure_archive', 'SCOPED'),
  ('public', 'org_enrollments', 'SCOPED'),
  ('public', 'organization_member_invites', 'SCOPED'),
  ('public', 'patient_comorbidity', 'SCOPED'),
  ('public', 'patient_content_rating_feedback', 'SCOPED'),
  ('public', 'patient_daily_warmup_presentations', 'SCOPED'),
  ('public', 'patient_daily_warmup_video_views', 'SCOPED'),
  ('public', 'patient_diary_day_snapshots', 'SCOPED'),
  ('public', 'patient_files', 'SCOPED'),
  ('public', 'patient_home_block_items', 'SCOPED'),
  ('public', 'patient_home_blocks', 'SCOPED'),
  ('public', 'patient_invites', 'SCOPED'),
  ('public', 'patient_lfk_assignments', 'SCOPED'),
  ('public', 'patient_merge_candidates', 'SCOPED'),
  ('public', 'patient_payment', 'SCOPED'),
  ('public', 'patient_practice_completions', 'SCOPED'),
  ('public', 'phone_challenges', 'BOOTSTRAP'),
  ('public', 'phone_messenger_bind_secrets', 'BOOTSTRAP'),
  ('public', 'platform_user_contacts', 'BOOTSTRAP'),
  ('public', 'platform_users', 'BOOTSTRAP'),
  ('public', 'product_analytics_events_recent', 'SCOPED'),
  ('public', 'product_analytics_user_hourly', 'SCOPED'),
  ('public', 'product_push_notifications', 'SCOPED'),
  ('public', 'program_action_log', 'SCOPED'),
  ('public', 'program_item_discussion_messages', 'SCOPED'),
  ('public', 'program_item_discussion_reads', 'SCOPED'),
  ('public', 'recommendation_regions', 'SCOPED'),
  ('public', 'recommendations', 'SCOPED'),
  ('public', 'reference_categories', 'SCOPED'),
  ('public', 'reference_items', 'SCOPED'),
  ('public', 'reminder_delivery_events', 'SCOPED'),
  ('public', 'reminder_journal', 'SCOPED'),
  ('public', 'reminder_occurrence_history', 'SCOPED'),
  ('public', 'reminder_rules', 'SCOPED'),
  ('public', 'saas_org_entitlement_overrides', 'SCOPED'),
  ('public', 'saas_organization_trials', 'SCOPED'),
  ('public', 'specialist_signup_intents', 'BOOTSTRAP'),
  ('public', 'specialist_tasks', 'SCOPED'),
  ('public', 'support_conversation_messages', 'SCOPED'),
  ('public', 'support_conversations', 'SCOPED'),
  ('public', 'support_delivery_events', 'SCOPED'),
  ('public', 'support_question_messages', 'SCOPED'),
  ('public', 'support_questions', 'SCOPED'),
  ('public', 'symptom_entries', 'SCOPED'),
  ('public', 'symptom_trackings', 'SCOPED'),
  ('public', 'system_settings', 'BOOTSTRAP'),
  ('public', 'system_settings_audit', 'BOOTSTRAP'),
  ('public', 'test_attempts', 'SCOPED'),
  ('public', 'test_results', 'SCOPED'),
  ('public', 'test_set_items', 'SCOPED'),
  ('public', 'test_sets', 'SCOPED'),
  ('public', 'tests', 'SCOPED'),
  ('public', 'treatment_program_events', 'SCOPED'),
  ('public', 'treatment_program_instance_stage_groups', 'SCOPED'),
  ('public', 'treatment_program_instance_stage_items', 'SCOPED'),
  ('public', 'treatment_program_instance_stages', 'SCOPED'),
  ('public', 'treatment_program_instances', 'SCOPED'),
  ('public', 'treatment_program_template_stage_groups', 'SCOPED'),
  ('public', 'treatment_program_template_stage_items', 'SCOPED'),
  ('public', 'treatment_program_template_stages', 'SCOPED'),
  ('public', 'treatment_program_templates', 'SCOPED'),
  ('public', 'user_channel_bindings', 'BOOTSTRAP'),
  ('public', 'user_channel_preferences', 'BOOTSTRAP'),
  ('public', 'user_email_setup_tokens', 'BOOTSTRAP'),
  ('public', 'user_notification_topic_channels', 'BOOTSTRAP'),
  ('public', 'user_notification_topics', 'BOOTSTRAP'),
  ('public', 'user_oauth_bindings', 'BOOTSTRAP'),
  ('public', 'user_password_credentials', 'BOOTSTRAP'),
  ('public', 'user_phone_history', 'BOOTSTRAP'),
  ('public', 'user_pins', 'BOOTSTRAP'),
  ('public', 'user_web_push_subscriptions', 'BOOTSTRAP'),
  ('public', 'webapp_reminder_occurrences', 'SCOPED');

\if :{?p0_5_down}
\echo 'P0.5 role split DOWN: revoking app grants and dropping roles when unused.'

SELECT format('REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLE %I.%I FROM %I', schema_name, table_name, :'p0_5_app_role')
FROM p0_5_app_grant_tables
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_app_role')
ORDER BY schema_name, table_name
\gexec

SELECT format('REVOKE USAGE, SELECT ON SEQUENCE %I.%I FROM %I', seq_ns.nspname, seq.relname, :'p0_5_app_role')
FROM pg_class seq
JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype = 'a'
JOIN pg_class tbl ON tbl.oid = dep.refobjid
JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
JOIN p0_5_app_grant_tables targets ON targets.schema_name = tbl_ns.nspname AND targets.table_name = tbl.relname
WHERE seq.relkind = 'S'
  AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_app_role')
ORDER BY seq_ns.nspname, seq.relname
\gexec

SELECT format('REVOKE USAGE ON SCHEMA %I FROM %I', schema_name, :'p0_5_app_role')
FROM (SELECT DISTINCT schema_name FROM p0_5_app_grant_tables) schemas
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_app_role')
ORDER BY schema_name
\gexec

SELECT format('REVOKE CONNECT ON DATABASE %I FROM %I', current_database(), :'p0_5_app_role')
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_app_role')
\gexec

SELECT format('REVOKE %I FROM %I', :'p0_5_owner_role', :'p0_5_migrator_role')
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_owner_role')
  AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_migrator_role')
\gexec

SELECT format('REVOKE %I FROM %I', :'p0_5_owner_role', :'p0_5_app_role')
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_owner_role')
  AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_app_role')
\gexec

SELECT format('REVOKE %I FROM %I', :'p0_5_migrator_role', :'p0_5_app_role')
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_migrator_role')
  AND EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_app_role')
\gexec

SELECT format('DROP ROLE %I', :'p0_5_app_role')
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_app_role')
\gexec

SELECT format('DROP ROLE %I', :'p0_5_migrator_role')
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_migrator_role')
\gexec

SELECT format('DROP ROLE %I', :'p0_5_owner_role')
WHERE EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_owner_role')
\gexec

\echo 'P0.5 role split DOWN complete.'
\else
\echo 'P0.5 role split UP: creating roles and granting SCOPED/BOOTSTRAP app DML.'

SELECT format('CREATE ROLE %I NOLOGIN BYPASSRLS', :'p0_5_owner_role')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_owner_role')
\gexec

SELECT format('CREATE ROLE %I LOGIN BYPASSRLS', :'p0_5_migrator_role')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_migrator_role')
\gexec

SELECT format('CREATE ROLE %I LOGIN NOBYPASSRLS', :'p0_5_app_role')
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = :'p0_5_app_role')
\gexec

ALTER ROLE :"p0_5_owner_role" NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS;
ALTER ROLE :"p0_5_migrator_role" LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION BYPASSRLS;
ALTER ROLE :"p0_5_app_role" LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;

GRANT :"p0_5_owner_role" TO :"p0_5_migrator_role";
REVOKE :"p0_5_owner_role" FROM :"p0_5_app_role";
REVOKE :"p0_5_migrator_role" FROM :"p0_5_app_role";

SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'p0_5_owner_role') \gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'p0_5_migrator_role') \gexec
SELECT format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), :'p0_5_app_role') \gexec

SELECT format('GRANT USAGE, CREATE ON SCHEMA %I TO %I', schema_name, :'p0_5_owner_role')
FROM (SELECT DISTINCT schema_name FROM p0_5_app_grant_tables) schemas
ORDER BY schema_name
\gexec

SELECT format('GRANT USAGE ON SCHEMA %I TO %I', schema_name, :'p0_5_app_role')
FROM (SELECT DISTINCT schema_name FROM p0_5_app_grant_tables) schemas
ORDER BY schema_name
\gexec

SELECT format('GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE %I.%I TO %I', schema_name, table_name, :'p0_5_app_role')
FROM p0_5_app_grant_tables
ORDER BY schema_name, table_name
\gexec

SELECT format('GRANT USAGE, SELECT ON SEQUENCE %I.%I TO %I', seq_ns.nspname, seq.relname, :'p0_5_app_role')
FROM pg_class seq
JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype = 'a'
JOIN pg_class tbl ON tbl.oid = dep.refobjid
JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
JOIN p0_5_app_grant_tables targets ON targets.schema_name = tbl_ns.nspname AND targets.table_name = tbl.relname
WHERE seq.relkind = 'S'
ORDER BY seq_ns.nspname, seq.relname
\gexec

SELECT (
  rolcanlogin = true
  AND rolsuper = false
  AND rolcreatedb = false
  AND rolcreaterole = false
  AND rolreplication = false
  AND rolbypassrls = false
)::int AS p0_5_app_role_safe_ok
FROM pg_roles
WHERE rolname = :'p0_5_app_role' \gset

\if :p0_5_app_role_safe_ok
\else
\echo 'FATAL: P0.5 app role must be LOGIN, non-superuser, non-createrole, and NOBYPASSRLS.'
SELECT 1 / 0 AS p0_5_abort;
\endif

-- MUST use pg_has_role(...) here, NOT a raw one-hop pg_auth_members lookup: pg_has_role follows the
-- FULL transitive membership chain, so it also catches e.g. app_role -> some_intermediary_role ->
-- owner_role, which a direct pg_auth_members row check would miss (it only sees a DIRECT grant and
-- would report "safe" even though the app role could still assume owner/migrator privileges through
-- an intermediary). Same fix/rationale as deploy/postgres/p0-5b-role-split-staff-patient.sql's
-- app_patient/app_staff assertion (docs/_TODO/SAAS_FOUNDATION/LOG.md, taskdb #655/#662).
SELECT (
  NOT pg_has_role(:'p0_5_app_role', :'p0_5_owner_role', 'MEMBER')
  AND NOT pg_has_role(:'p0_5_app_role', :'p0_5_migrator_role', 'MEMBER')
)::int AS p0_5_app_membership_safe_ok \gset

\if :p0_5_app_membership_safe_ok
\else
\echo 'FATAL: P0.5 app role must not be a member of owner or migrator roles.'
SELECT 1 / 0 AS p0_5_abort;
\endif

\echo 'P0.5 role split UP complete.'
\endif
