ALTER TABLE telegram_users
  ADD COLUMN IF NOT EXISTS notify_spb BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS notify_msk BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS notify_online BOOLEAN NOT NULL DEFAULT false;
