/**
 * Canonical keys for periodic job ticks in `public.operator_job_status` (mirror integrator schema if applicable).
 *
 * Значения живут в `backgroundJobManifest.ts` — единственном typed manifest фоновых заданий (этап 2
 * сводного аудита 27.08.2026). Здесь остаётся только привычный вход по имени константы, чтобы
 * маршруты и health-читатели не импортировали manifest целиком.
 */
export {
  OPERATOR_MEDIA_JOB_FAMILY,
  OPERATOR_MEDIA_TRANSCODE_RECONCILE_JOB_KEY,
  OPERATOR_MEDIA_PENDING_DELETE_PURGE_JOB_KEY,
  OPERATOR_MEDIA_MULTIPART_CLEANUP_JOB_KEY,
  OPERATOR_MEDIA_PREVIEW_PROCESS_JOB_KEY,
  OPERATOR_MEDIA_PLAYBACK_STATS_RETENTION_JOB_KEY,
  OPERATOR_MEDIA_HLS_PROXY_ERRORS_RETENTION_JOB_KEY,
  OPERATOR_ANALYTICS_JOB_FAMILY,
  OPERATOR_PRODUCT_ANALYTICS_RETENTION_JOB_KEY,
  OPERATOR_HEALTH_JOB_FAMILY,
  OPERATOR_SYSTEM_HEALTH_GUARD_TICK_JOB_KEY,
  OPERATOR_HEALTH_CRITICAL_TICK_JOB_KEY,
  OPERATOR_HEALTH_DIGEST_TICK_JOB_KEY,
  OPERATOR_OUTBOUND_PROBE_JOB_KEY,
  OPERATOR_BACKUP_JOB_FAMILY,
  OPERATOR_SAAS_BILLING_JOB_FAMILY,
  OPERATOR_SAAS_BILLING_RENEWAL_TICK_JOB_KEY,
  OPERATOR_MAINTENANCE_JOB_FAMILY,
  OPERATOR_DB_JOURNAL_RETENTION_JOB_KEY,
} from '@/modules/operator-health/backgroundJobManifest';
