#!/usr/bin/env bash
# Future TEST domain cutover preparation.  It is inert unless an operator passes
# --apply after a separate owner activation command.
set -euo pipefail

ACTION=preflight
OFFLINE=0
HOST_MAP=""
OUT=""

usage() { cat <<'EOF'
Usage: bash deploy/host/therapysto-domain-cutover.sh --host-map FILE [--offline] [--render FILE|--apply]

FILE is shell assignments (no secrets): STAFF_HOST, PLATFORM_ADMIN_HOST,
PATIENT_DEFAULT_HOST, PATIENT_BRANDED_HOST, CLINIC_CUSTOM_HOST,
TLS_CERTIFICATE_PATH and TLS_CERTIFICATE_KEY_PATH. All five hosts
must be distinct, valid DNS hostnames.  The script never supplies TEST names.
Default action is a non-mutating preflight. --render writes an nginx candidate;
--apply is intentionally owner-gated and is the only mode that can touch nginx.
EOF
}
die() { echo "FATAL: $*" >&2; exit 1; }

while (($#)); do case "$1" in
  --host-map) HOST_MAP=${2:-}; shift 2;; --offline) OFFLINE=1; shift;;
  --render) ACTION=render; OUT=${2:-}; shift 2;; --apply) ACTION=apply; shift;;
  -h|--help) usage; exit 0;; *) die "unknown argument: $1";; esac; done

[[ -n "$HOST_MAP" && -f "$HOST_MAP" ]] || die "--host-map FILE is required"
# shellcheck disable=SC1090
source "$HOST_MAP"
for key in STAFF_HOST PLATFORM_ADMIN_HOST PATIENT_DEFAULT_HOST PATIENT_BRANDED_HOST CLINIC_CUSTOM_HOST; do
  value=${!key:-}
  [[ "$value" =~ ^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$ ]] || die "$key must be a lowercase DNS hostname"
done
hosts=("$STAFF_HOST" "$PLATFORM_ADMIN_HOST" "$PATIENT_DEFAULT_HOST" "$PATIENT_BRANDED_HOST" "$CLINIC_CUSTOM_HOST")
[[ $(printf '%s\n' "${hosts[@]}" | sort -u | wc -l) -eq 5 ]] || die "host map values must be distinct"
[[ "$PATIENT_BRANDED_HOST" != "$CLINIC_CUSTOM_HOST" ]] || die "technical branded host must redirect to custom host"

cert_path=${TLS_CERTIFICATE_PATH:-}
key_path=${TLS_CERTIFICATE_KEY_PATH:-}
[[ -n "$cert_path" && -n "$key_path" && "$cert_path" = /* && "$key_path" = /* ]] || die "TLS_CERTIFICATE_PATH and TLS_CERTIFICATE_KEY_PATH must be absolute paths"
render() { cat <<EOF
# Generated by therapysto-domain-cutover.sh; do not activate without owner command.
server { listen 80 default_server; server_name _; return 444; }
server { listen 443 ssl http2 default_server; server_name _; return 444; }
server { listen 80; server_name $STAFF_HOST $PLATFORM_ADMIN_HOST $PATIENT_DEFAULT_HOST $PATIENT_BRANDED_HOST $CLINIC_CUSTOM_HOST; return 301 https://\$host\$request_uri; }
server {
  listen 443 ssl http2;
  server_name $STAFF_HOST $PLATFORM_ADMIN_HOST $PATIENT_DEFAULT_HOST $CLINIC_CUSTOM_HOST;
  ssl_certificate $cert_path;
  ssl_certificate_key /etc/letsencrypt/live/$PATIENT_DEFAULT_HOST/privkey.pem;
  location / { proxy_pass http://127.0.0.1:6300; proxy_http_version 1.1; proxy_set_header Host \$host; proxy_set_header X-Forwarded-Host \$host; proxy_set_header X-Forwarded-Proto \$scheme; proxy_set_header X-Real-IP \$remote_addr; proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for; proxy_set_header Upgrade \$http_upgrade; proxy_set_header Connection "upgrade"; }
}
server {
  listen 443 ssl http2;
  server_name $PATIENT_BRANDED_HOST;
  ssl_certificate $cert_path;
  ssl_certificate_key /etc/letsencrypt/live/$PATIENT_DEFAULT_HOST/privkey.pem;
  return 308 https://$CLINIC_CUSTOM_HOST\$request_uri;
}
EOF
}

[[ $OFFLINE -eq 1 ]] || { [[ -r "$cert_path" && -r "$key_path" ]] || die "certificate or key is missing"; }
[[ $OFFLINE -eq 1 ]] || for host in "${hosts[@]}"; do openssl x509 -in "$cert_path" -noout -checkhost "$host" >/dev/null || die "certificate does not cover: $host"; done
[[ $OFFLINE -eq 1 ]] || for host in "${hosts[@]}"; do getent ahosts "$host" >/dev/null || die "DNS does not resolve: $host"; done
if [[ "$ACTION" == render ]]; then [[ -n "$OUT" ]] || die "--render requires FILE"; render >"$OUT"; echo "rendered: $OUT"; exit 0; fi
if [[ "$ACTION" == apply ]]; then
  [[ "${THERAPYSTO_CUTOVER_OWNER_APPROVED:-}" == "yes" ]] || die "refusing apply: require THERAPYSTO_CUTOVER_OWNER_APPROVED=yes"
  tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT; render >"$tmp"; sudo nginx -t; sudo install -m 0644 "$tmp" /etc/nginx/sites-available/test.bersoncare.ru; sudo nginx -t; sudo systemctl reload nginx
fi
echo "preflight OK (${OFFLINE:+offline })"
