import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const dir = mkdtempSync(join(tmpdir(), 'therapysto-domain-'));
const map = join(dir, 'hosts.env');
const validMap = 'STAFF_HOST=staff.test.example\nPLATFORM_ADMIN_HOST=admin.test.example\nPATIENT_DEFAULT_HOST=therapygo.test.example\nPATIENT_BRANDED_HOST=bersoncare.therapygo.test.example\nCLINIC_CUSTOM_HOST=app.bersoncare.test.example\nEXPECTED_DNS_TARGET=192.0.2.10\nPLATFORM_TLS_CERTIFICATE_PATH=/tmp/platform-cert.pem\nPLATFORM_TLS_CERTIFICATE_KEY_PATH=/tmp/platform-key.pem\nCLINIC_TLS_CERTIFICATE_PATH=/tmp/clinic-cert.pem\nCLINIC_TLS_CERTIFICATE_KEY_PATH=/tmp/clinic-key.pem\nAPP_BASE_URL=https://staff.test.example\nPATIENT_APP_ORIGIN=https://therapygo.test.example\nYANDEX_OAUTH_REDIRECT_URIS=https://therapygo.test.example/api/auth/oauth/callback/yandex,https://app.bersoncare.test.example/api/auth/oauth/callback/yandex\nCERT_EXPIRY_WARN_DAYS=30\n';
writeFileSync(map, validMap);
const out = join(dir, 'nginx.conf');
execFileSync('bash', ['deploy/host/therapysto-domain-cutover.sh', '--host-map', map, '--offline', '--render', out]);
const config = readFileSync(out, 'utf8');
assert.match(config, /server_name _; return 444/);
assert.match(config, /proxy_set_header Host \$host/);
assert.match(config, /test\.bersoncare\.ru/);
assert.match(config, /ssl_certificate_key \/tmp\/platform-key\.pem/);
assert.match(config, /ssl_certificate_key \/tmp\/clinic-key\.pem/);
assert.match(config, /bersoncare\.therapygo\.test\.example;[\s\S]*return 308 https:\/\/app\.bersoncare\.test\.example\$request_uri/);
writeFileSync(map, validMap.replace('STAFF_HOST=staff.test.example', 'STAFF_HOST=bad_host'));
assert.throws(() => execFileSync('bash', ['deploy/host/therapysto-domain-cutover.sh', '--host-map', map, '--offline']), /lowercase DNS hostname/);
console.log('therapysto domain cutover contracts: PASS');
