/**
 * GENERATED — do not edit by hand.
 *
 * Produced by `apps/webapp/scripts/generate-drizzle-insert-surface.ts`
 * from live Drizzle metadata plus an AST/import-graph scan of `apps/webapp/src`. Regenerate with:
 *
 *   pnpm --dir apps/webapp exec tsx scripts/generate-drizzle-insert-surface.ts
 *
 * `pnpm test:db-privileges` runs the byte-equal `--check` first, so a schema change that does not
 * regenerate this file fails before any privilege test runs.
 *
 * WHAT EACH FIELD MEANS
 *   insertColumns          every column Drizzle NAMES in `INSERT INTO <relation> (...)` — the whole
 *                          schema column list minus columns whose `generated.type !== 'byDefault'`
 *                          (`generatedAlwaysAs`, `generatedAlwaysAsIdentity`). Postgres demands
 *                          column-level INSERT privilege on every named column even where the
 *                          value is the `DEFAULT` keyword, so a `defaultRandom()` primary key
 *                          belongs here even though no callsite ever sets it.
 *   directInsertCallsites  every `.insert(<export>)` in `apps/webapp/src` bound to this relation,
 *                          resolved through the import graph. EMPTY means no proven direct Drizzle
 *                          insert: the declaration must NOT widen such a relation's grant from ORM
 *                          metadata — its column grant serves raw SQL or a SECURITY DEFINER body
 *                          that names its own columns.
 *
 * This artifact is data, not authority. It grants nothing by itself: `declaration.ts` widens only
 * the column-level INSERT of relations that have a callsite here AND a role with a webapp
 * `purpose: 'relation'` capability, and it never removes a declared column.
 */

export interface DrizzleInsertRelation {
  readonly insertColumns: readonly string[];
  readonly directInsertCallsites: readonly string[];
}

export const DRIZZLE_INSERT_SURFACE: Readonly<Record<string, DrizzleInsertRelation>> = {
  'public.admin_audit_log': {
    insertColumns: [
      'action',
      'actor_id',
      'conflict_key',
      'created_at',
      'details',
      'id',
      'last_seen_at',
      'organization_id',
      'repeat_count',
      'resolved_at',
      'status',
      'target_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgOrganizationProvisioning.ts:262',
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:147',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:1072',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:1447',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:1769',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:449',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:913',
    ],
  },
  'public.auth_rate_limit_events': {
    insertColumns: [
      'key',
      'occurred_at',
      'scope',
    ],
    directInsertCallsites: [],
  },
  'public.be_appointment_cancellations': {
    insertColumns: [
      'actor_id',
      'actor_type',
      'applied_policy_id',
      'applied_policy_snapshot',
      'appointment_id',
      'cancellation_type',
      'created_at',
      'id',
      'manual_override',
      'notifications_sent',
      'organization_id',
      'package_session_charged',
      'prepayment_refunded',
      'prepayment_retained',
      'reason',
      'staff_comment',
      'was_free',
      'was_penalized',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:557',
    ],
  },
  'public.be_appointment_history_events': {
    insertColumns: [
      'actor_id',
      'appointment_id',
      'created_at',
      'event_type',
      'id',
      'occurred_at',
      'organization_id',
      'payload',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:460',
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:584',
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:723',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:2030',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:2080',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:417',
    ],
  },
  'public.be_appointment_no_shows': {
    insertColumns: [
      'actor_id',
      'actor_type',
      'appointment_id',
      'created_at',
      'id',
      'manual_override',
      'notifications_sent',
      'organization_id',
      'reason',
      'staff_comment',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:705',
    ],
  },
  'public.be_appointment_reschedules': {
    insertColumns: [
      'actor_id',
      'actor_type',
      'applied_policy_id',
      'applied_policy_snapshot',
      'appointment_id',
      'created_at',
      'free_cancellation_available_after',
      'free_cancellation_available_at_reschedule',
      'from_end_at',
      'from_start_at',
      'id',
      'manual_override',
      'notifications_sent',
      'organization_id',
      'reason',
      'staff_comment',
      'to_end_at',
      'to_start_at',
      'was_in_free_reschedule_window',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:429',
    ],
  },
  'public.be_appointment_staff_comments': {
    insertColumns: [
      'appointment_id',
      'author_id',
      'body',
      'created_at',
      'id',
      'organization_id',
      'platform_user_id',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgClientHistory.ts:1080',
    ],
  },
  'public.be_appointments': {
    insertColumns: [
      'appointment_reminder_allowed_preset_ids',
      'appointment_reminder_preset_id',
      'appointment_reminder_selection_source',
      'attribution_json',
      'branch_id',
      'chain_id',
      'chain_position',
      'created_at',
      'deleted_at',
      'duration_minutes',
      'end_at',
      'id',
      'organization_id',
      'original_start_at',
      'package_usage_ref',
      'payment_ref',
      'phone_normalized',
      'platform_user_id',
      'reschedule_count',
      'room_id',
      'service_id',
      'source',
      'specialist_id',
      'start_at',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:2005',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:387',
    ],
  },
  'public.be_availability_rules': {
    insertColumns: [
      'branch_id',
      'config',
      'created_at',
      'id',
      'is_active',
      'organization_id',
      'rule_type',
      'specialist_id',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingScheduling.ts:637',
    ],
  },
  'public.be_booking_form_fields': {
    insertColumns: [
      'created_at',
      'field_key',
      'field_type',
      'id',
      'is_active',
      'is_required',
      'label',
      'organization_id',
      'placeholder',
      'sort_order',
      'updated_at',
      'visible_to_patient',
      'visible_to_staff',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingForm.ts:169',
    ],
  },
  'public.be_booking_form_submissions': {
    insertColumns: [
      'appointment_id',
      'created_at',
      'field_id',
      'id',
      'organization_id',
      'value_text',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingForm.ts:220',
    ],
  },
  'public.be_branches': {
    insertColumns: [
      'address',
      'city_code',
      'color',
      'created_at',
      'id',
      'is_active',
      'organization_id',
      'short_title',
      'sort_order',
      'timezone',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:840',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:898',
    ],
  },
  'public.be_cancellation_policies': {
    insertColumns: [
      'cancellation_allowed',
      'charge_package_session_on_late',
      'created_at',
      'free_cancel_hours_before',
      'id',
      'is_active',
      'late_cancellation_behavior',
      'notify_patient',
      'notify_staff',
      'organization_id',
      'refund_prepayment_on_late',
      'requires_staff_confirmation',
      'scope_entity_id',
      'scope_level',
      'sort_order',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingPolicies.ts:261',
    ],
  },
  'public.be_clinic_services': {
    insertColumns: [
      'admin_manual_only',
      'buffer_after_minutes',
      'created_at',
      'description',
      'duration_minutes',
      'id',
      'is_active',
      'online_payment_applicable',
      'organization_id',
      'prepayment_applicable',
      'price_minor',
      'public_widget_visible',
      'sort_order',
      'title',
      'updated_at',
      'usable_in_packages',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1154',
    ],
  },
  'public.be_organization_members': {
    insertColumns: [
      'created_at',
      'doctor_screens_disabled',
      'id',
      'organization_id',
      'platform_user_id',
      'role',
      'specialist_id',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.be_organizations': {
    insertColumns: [
      'cabinet_first_entered_at',
      'created_at',
      'id',
      'is_active',
      'sort_order',
      'tariff_id',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.be_package_history_events': {
    insertColumns: [
      'event_type',
      'id',
      'occurred_at',
      'organization_id',
      'patient_package_id',
      'payload_json',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgMemberships.ts:1027',
      'apps/webapp/src/infra/repos/pgMemberships.ts:852',
      'apps/webapp/src/infra/repos/pgMemberships.ts:915',
      'apps/webapp/src/infra/repos/pgMemberships.ts:980',
    ],
  },
  'public.be_package_items': {
    insertColumns: [
      'created_at',
      'id',
      'package_id',
      'quantity',
      'service_id',
      'sort_order',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgMemberships.ts:393',
    ],
  },
  'public.be_package_usages': {
    insertColumns: [
      'appointment_id',
      'comment',
      'created_at',
      'created_by_platform_user_id',
      'id',
      'occurred_at',
      'organization_id',
      'patient_package_id',
      'patient_package_item_id',
      'quantity',
      'usage_kind',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgMemberships.ts:1006',
      'apps/webapp/src/infra/repos/pgMemberships.ts:767',
      'apps/webapp/src/infra/repos/pgMemberships.ts:819',
      'apps/webapp/src/infra/repos/pgMemberships.ts:835',
      'apps/webapp/src/infra/repos/pgMemberships.ts:887',
      'apps/webapp/src/infra/repos/pgMemberships.ts:958',
    ],
  },
  'public.be_patient_booking_profiles': {
    insertColumns: [
      'booking_blocked',
      'id',
      'is_problematic',
      'no_show_count',
      'organization_id',
      'platform_user_id',
      'problematic_note',
      'updated_at',
      'updated_by',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgClientHistory.ts:1035',
    ],
  },
  'public.be_patient_package_items': {
    insertColumns: [
      'created_at',
      'id',
      'patient_package_id',
      'quantity_initial',
      'service_id',
      'sort_order',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgMemberships.ts:496',
      'apps/webapp/src/infra/repos/pgMemberships.ts:539',
    ],
  },
  'public.be_patient_packages': {
    insertColumns: [
      'assigned_by_platform_user_id',
      'checkout_url',
      'created_at',
      'currency',
      'deduction_mode',
      'display_number',
      'id',
      'notes',
      'organization_id',
      'paid_amount_minor',
      'paid_currency',
      'payment_intent_id',
      'payment_ref',
      'platform_user_id',
      'price_minor',
      'sale_idempotency_key',
      'sold_at',
      'status',
      'subscription_package_id',
      'title',
      'updated_at',
      'valid_from',
      'valid_until',
      'validity_days',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgMemberships.ts:472',
      'apps/webapp/src/infra/repos/pgMemberships.ts:519',
    ],
  },
  'public.be_patient_timeline_events': {
    insertColumns: [
      'created_at',
      'domain',
      'event_type',
      'id',
      'linked_object_id',
      'linked_object_type',
      'occurred_at',
      'organization_id',
      'payload',
      'platform_user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:475',
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:593',
      'apps/webapp/src/infra/repos/pgBookingAppointmentLifecycle.ts:732',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:2039',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:2089',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:426',
    ],
  },
  'public.be_payment_history_events': {
    insertColumns: [
      'amount_minor',
      'appointment_id',
      'comment',
      'currency',
      'event_type',
      'id',
      'occurred_at',
      'organization_id',
      'payload_json',
      'payment_id',
      'platform_user_id',
      'provider_id',
      'purpose',
      'refund_id',
      'status',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPayments.ts:632',
    ],
  },
  'public.be_payment_intents': {
    insertColumns: [
      'amount_minor',
      'appointment_id',
      'checkout_url',
      'created_at',
      'currency',
      'id',
      'idempotency_key',
      'metadata_json',
      'organization_id',
      'platform_user_id',
      'product_ref',
      'provider_id',
      'provider_intent_ref',
      'purpose',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPayments.ts:339',
    ],
  },
  'public.be_payment_provider_events': {
    insertColumns: [
      'created_at',
      'event_type',
      'id',
      'idempotency_key',
      'intent_ref',
      'organization_id',
      'payload_json',
      'processed_at',
      'provider_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPayments.ts:545',
    ],
  },
  'public.be_payments': {
    insertColumns: [
      'amount_minor',
      'appointment_id',
      'captured_at',
      'created_at',
      'currency',
      'id',
      'organization_id',
      'payment_intent_id',
      'platform_user_id',
      'provider_id',
      'purpose',
      'status',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPayments.ts:473',
    ],
  },
  'public.be_prepayment_policies': {
    insertColumns: [
      'amount_minor',
      'created_at',
      'currency',
      'id',
      'is_active',
      'mode',
      'online_category',
      'organization_id',
      'percent_bps',
      'service_id',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPayments.ts:235',
    ],
  },
  'public.be_refunds': {
    insertColumns: [
      'amount_minor',
      'appointment_id',
      'created_at',
      'currency',
      'id',
      'organization_id',
      'payment_id',
      'provider_refund_ref',
      'reason',
      'status',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPayments.ts:526',
    ],
  },
  'public.be_reschedule_policies': {
    insertColumns: [
      'allow_different_branch',
      'allow_different_city',
      'allow_different_service',
      'allow_different_specialist',
      'created_at',
      'id',
      'is_active',
      'limit_exceeded_behavior',
      'max_self_reschedules',
      'notify_patient',
      'notify_staff',
      'organization_id',
      'requires_staff_confirmation',
      'scope_entity_id',
      'scope_level',
      'self_reschedule_hours_before',
      'sort_order',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingPolicies.ts:333',
    ],
  },
  'public.be_rooms': {
    insertColumns: [
      'branch_id',
      'created_at',
      'id',
      'is_active',
      'organization_id',
      'sort_order',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:969',
    ],
  },
  'public.be_schedule_blocks': {
    insertColumns: [
      'block_type',
      'branch_id',
      'created_at',
      'created_by_actor_id',
      'end_at',
      'id',
      'organization_id',
      'room_id',
      'specialist_id',
      'start_at',
      'title',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingScheduling.ts:712',
    ],
  },
  'public.be_schedule_templates': {
    insertColumns: [
      'branch_id',
      'breaks',
      'created_at',
      'end_minute',
      'id',
      'is_active',
      'name',
      'organization_id',
      'sort_order',
      'start_minute',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingScheduling.ts:1017',
    ],
  },
  'public.be_service_location_availability': {
    insertColumns: [
      'branch_id',
      'created_at',
      'id',
      'is_active',
      'organization_id',
      'service_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1306',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1371',
    ],
  },
  'public.be_specialist_locations': {
    insertColumns: [
      'branch_id',
      'created_at',
      'id',
      'is_active',
      'organization_id',
      'specialist_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1065',
    ],
  },
  'public.be_specialist_rooms': {
    insertColumns: [
      'created_at',
      'id',
      'is_active',
      'organization_id',
      'room_id',
      'specialist_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1082',
    ],
  },
  'public.be_specialist_service_availability': {
    insertColumns: [
      'branch_id',
      'city_code',
      'created_at',
      'id',
      'is_active',
      'organization_id',
      'price_minor_override',
      'room_id',
      'service_id',
      'sort_order',
      'specialist_id',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1216',
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1435',
    ],
  },
  'public.be_specialists': {
    insertColumns: [
      'appointment_reminder_allowed_preset_ids',
      'appointment_reminder_default_preset_id',
      'created_at',
      'description',
      'full_name',
      'id',
      'is_active',
      'organization_id',
      'sort_order',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1037',
      'apps/webapp/src/infra/repos/pgOrganizationProvisioning.ts:229',
    ],
  },
  'public.be_subscription_packages': {
    insertColumns: [
      'created_at',
      'currency',
      'deduction_mode',
      'description',
      'id',
      'is_active',
      'organization_id',
      'price_minor',
      'title',
      'updated_at',
      'validity_days',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgMemberships.ts:375',
    ],
  },
  'public.be_working_days': {
    insertColumns: [
      'branch_id',
      'breaks',
      'created_at',
      'end_minute',
      'id',
      'is_closed',
      'organization_id',
      'room_id',
      'specialist_id',
      'start_minute',
      'updated_at',
      'work_date',
    ],
    directInsertCallsites: [],
  },
  'public.be_working_hours': {
    insertColumns: [
      'branch_id',
      'created_at',
      'end_minute',
      'id',
      'is_active',
      'organization_id',
      'room_id',
      'specialist_id',
      'start_minute',
      'updated_at',
      'weekday',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingScheduling.ts:802',
    ],
  },
  'public.booking_cities': {
    insertColumns: [
      'code',
      'created_at',
      'id',
      'is_active',
      'sort_order',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.broadcast_audit': {
    insertColumns: [
      'actor_id',
      'attach_menu_after_send',
      'audience_filter',
      'audience_size',
      'blocked_recipient_count',
      'category',
      'channels',
      'delivery_jobs_total',
      'error_count',
      'executed_at',
      'id',
      'message_body',
      'message_title',
      'organization_id',
      'preview_only',
      'sent_count',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBroadcastAudit.ts:33',
      'apps/webapp/src/infra/repos/pgDoctorBroadcastDelivery.ts:43',
    ],
  },
  'public.broadcast_audit_recipients': {
    insertColumns: [
      'audit_id',
      'organization_id',
      'platform_user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgDoctorBroadcastDelivery.ts:87',
    ],
  },
  'public.channel_link_secrets': {
    insertColumns: [
      'channel_code',
      'created_at',
      'expires_at',
      'id',
      'token_hash',
      'used_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.clinic_public_directory_entries': {
    insertColumns: [
      'card_is_published',
      'created_at',
      'description',
      'display_name',
      'is_published',
      'locations_json',
      'logo_media_id',
      'organization_id',
      'photo_media_ids',
      'public_contact_email',
      'public_contact_phone',
      'public_website_url',
      'published_at',
      'slug',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgClinicDirectory.ts:273',
    ],
  },
  'public.clinical_anamnesis_illness': {
    insertColumns: [
      'comment',
      'created_at',
      'created_by',
      'id',
      'organization_id',
      'patient_user_id',
      'period',
      'what',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:896',
    ],
  },
  'public.clinical_anamnesis_lifestyle': {
    insertColumns: [
      'created_at',
      'created_by',
      'id',
      'organization_id',
      'patient_user_id',
      'record_date',
      'text',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:917',
    ],
  },
  'public.clinical_anamnesis_trauma': {
    insertColumns: [
      'created_at',
      'created_by',
      'id',
      'immobilization',
      'organization_id',
      'patient_user_id',
      'type',
      'what',
      'year',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:868',
    ],
  },
  'public.clinical_complaint': {
    insertColumns: [
      'created_at',
      'description',
      'id',
      'organization_id',
      'patient_user_id',
      'priority',
      'resolved_at',
      'source_visit_id',
      'status',
      'text',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:484',
    ],
  },
  'public.clinical_complaint_update': {
    insertColumns: [
      'complaint_id',
      'created_at',
      'id',
      'note',
      'organization_id',
      'resolved',
      'severity',
      'visit_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:498',
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:536',
    ],
  },
  'public.clinical_diagnosis': {
    insertColumns: [
      'catalog_id',
      'clinical_status',
      'comment',
      'created_at',
      'id',
      'organization_id',
      'patient_user_id',
      'priority',
      'resolved_at',
      'source_visit_id',
      'status',
      'text',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:508',
    ],
  },
  'public.clinical_diagnosis_catalog': {
    insertColumns: [
      'created_at',
      'created_by',
      'id',
      'label',
      'note',
      'organization_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:424',
    ],
  },
  'public.clinical_diagnosis_status_history': {
    insertColumns: [
      'changed_at',
      'changed_by',
      'diagnosis_id',
      'id',
      'new_status',
      'note',
      'old_status',
      'organization_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:743',
    ],
  },
  'public.clinical_diagnosis_update': {
    insertColumns: [
      'created_at',
      'diagnosis_id',
      'id',
      'organization_id',
      'refinement',
      'removed',
      'status',
      'visit_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:577',
    ],
  },
  'public.clinical_test_regions': {
    insertColumns: [
      'body_region_id',
      'clinical_test_id',
      'organization_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgClinicalTests.ts:465',
      'apps/webapp/src/infra/repos/pgClinicalTests.ts:535',
    ],
  },
  'public.clinical_visit': {
    insertColumns: [
      'anamnesis_text',
      'canonical_appointment_id',
      'created_at',
      'created_by',
      'duration',
      'exam',
      'id',
      'location',
      'manipulations',
      'organization_id',
      'patient_user_id',
      'recommendations',
      'service',
      'trial_results',
      'visit_type',
      'visited_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgBookingEngine.ts:1952',
      'apps/webapp/src/infra/repos/pgPatientClinical.ts:460',
    ],
  },
  'public.comments': {
    insertColumns: [
      'author_id',
      'body',
      'comment_type',
      'created_at',
      'id',
      'organization_id',
      'target_id',
      'target_type',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgComments.ts:74',
    ],
  },
  'public.contacts': {
    insertColumns: [
      'created_at',
      'id',
      'is_primary',
      'label',
      'type',
      'updated_at',
      'user_id',
      'value_normalized',
    ],
    directInsertCallsites: [],
  },
  'public.content_access_grants': {
    insertColumns: [
      'content_id',
      'created_at',
      'expires_at',
      'id',
      'meta_json',
      'purpose',
      'revoked_at',
      'token_hash',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.content_access_grants_webapp': {
    insertColumns: [
      'content_id',
      'created_at',
      'expires_at',
      'id',
      'integrator_grant_id',
      'meta_json',
      'organization_id',
      'platform_user_id',
      'purpose',
      'revoked_at',
      'token_hash',
    ],
    directInsertCallsites: [],
  },
  'public.content_pages': {
    insertColumns: [
      'archived_at',
      'body_html',
      'body_md',
      'created_at',
      'deleted_at',
      'id',
      'image_url',
      'is_published',
      'linked_course_id',
      'organization_id',
      'requires_auth',
      'section',
      'slug',
      'sort_order',
      'summary',
      'title',
      'updated_at',
      'video_type',
      'video_url',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgContentPages.ts:225',
    ],
  },
  'public.content_section_slug_history': {
    insertColumns: [
      'changed_by_user_id',
      'created_at',
      'id',
      'new_slug',
      'old_slug',
      'organization_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgContentSections.ts:381',
    ],
  },
  'public.content_sections': {
    insertColumns: [
      'cover_image_url',
      'created_at',
      'description',
      'icon_image_url',
      'id',
      'is_visible',
      'kind',
      'organization_id',
      'requires_auth',
      'slug',
      'sort_order',
      'system_parent_code',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgContentSections.ts:205',
    ],
  },
  'public.conversation_messages': {
    insertColumns: [
      'conversation_id',
      'created_at',
      'external_chat_id',
      'external_message_id',
      'id',
      'sender_role',
      'source',
      'text',
    ],
    directInsertCallsites: [],
  },
  'public.conversations': {
    insertColumns: [
      'admin_scope',
      'close_reason',
      'closed_at',
      'id',
      'last_message_at',
      'opened_at',
      'source',
      'status',
      'user_identity_id',
    ],
    directInsertCallsites: [],
  },
  'public.courses': {
    insertColumns: [
      'access_settings',
      'created_at',
      'currency',
      'description',
      'id',
      'intro_lesson_page_id',
      'organization_id',
      'price_minor',
      'program_template_id',
      'status',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgCourses.ts:331',
    ],
  },
  'public.doctor_notes': {
    insertColumns: [
      'author_id',
      'created_at',
      'id',
      'organization_id',
      'text',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgDoctorNotes.ts:48',
    ],
  },
  'public.doctor_patient_support': {
    insertColumns: [
      'birth_date',
      'comments_enabled',
      'gender',
      'height_cm',
      'id',
      'media_enabled',
      'on_support',
      'organization_id',
      'patient_user_id',
      'support_started_at',
      'updated_at',
      'updated_by',
      'weight_kg',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgDoctorPatientSupport.ts:110',
      'apps/webapp/src/infra/repos/pgDoctorPatientSupport.ts:137',
    ],
  },
  'public.email_challenges': {
    insertColumns: [
      'attempts',
      'code_hash',
      'created_at',
      'delivery_claimed_at',
      'delivery_token',
      'email',
      'expires_at',
      'id',
      'pending_delivery_code',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.email_send_cooldowns': {
    insertColumns: [
      'email_normalized',
      'last_sent_at',
      'user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgReminderTransactionalEmailCooldown.ts:42',
    ],
  },
  'public.idempotency_keys': {
    insertColumns: [
      'expires_at',
      'key',
      'request_hash',
      'response_body',
      'status',
    ],
    directInsertCallsites: [],
  },
  'public.identities': {
    insertColumns: [
      'created_at',
      'external_id',
      'id',
      'resource',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.integration_data_quality_incidents': {
    insertColumns: [
      'entity',
      'error_reason',
      'external_id',
      'field',
      'first_seen_at',
      'id',
      'integration',
      'last_seen_at',
      'occurrences',
      'raw_value',
      'status',
      'timezone_used',
    ],
    directInsertCallsites: [],
  },
  'public.integration_webhook_error_events': {
    insertColumns: [
      'error_class',
      'id',
      'occurred_at',
      'source',
    ],
    directInsertCallsites: [],
  },
  'public.integration_webhook_last_status': {
    insertColumns: [
      'detail',
      'error_class',
      'http_status_returned',
      'processed_ok',
      'received_at',
      'source',
    ],
    directInsertCallsites: [],
  },
  'public.lfk_complex_exercises': {
    insertColumns: [
      'comment',
      'complex_id',
      'exercise_id',
      'id',
      'local_comment',
      'max_pain_0_10',
      'organization_id',
      'reps',
      'sets',
      'side',
      'sort_order',
    ],
    directInsertCallsites: [],
  },
  'public.lfk_complex_template_exercises': {
    insertColumns: [
      'comment',
      'exercise_id',
      'id',
      'max_pain_0_10',
      'organization_id',
      'owner_kind',
      'reps',
      'sets',
      'side',
      'sort_order',
      'template_id',
    ],
    directInsertCallsites: [],
  },
  'public.lfk_complex_templates': {
    insertColumns: [
      'created_at',
      'created_by',
      'description',
      'id',
      'organization_id',
      'owner_kind',
      'status',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.lfk_complexes': {
    insertColumns: [
      'created_at',
      'diagnosis_ref_id',
      'diagnosis_text',
      'id',
      'is_active',
      'organization_id',
      'origin',
      'platform_user_id',
      'region_ref_id',
      'side',
      'symptom_tracking_id',
      'title',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.lfk_exercise_media': {
    insertColumns: [
      'created_at',
      'exercise_id',
      'id',
      'media_type',
      'media_url',
      'organization_id',
      'owner_kind',
      'sort_order',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:1157',
    ],
  },
  'public.lfk_exercise_regions': {
    insertColumns: [
      'exercise_id',
      'organization_id',
      'owner_kind',
      'region_ref_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:1147',
    ],
  },
  'public.lfk_exercises': {
    insertColumns: [
      'catalog_scope',
      'contraindications',
      'created_at',
      'created_by',
      'description',
      'difficulty_1_10',
      'id',
      'is_archived',
      'load_type',
      'organization_id',
      'owner_kind',
      'region_ref_id',
      'tags',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:1128',
    ],
  },
  'public.lfk_sessions': {
    insertColumns: [
      'comment',
      'completed_at',
      'complex_id',
      'created_at',
      'difficulty_0_10',
      'duration_minutes',
      'id',
      'organization_id',
      'pain_0_10',
      'recorded_at',
      'source',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.login_tokens': {
    insertColumns: [
      'confirmed_at',
      'created_at',
      'expires_at',
      'id',
      'method',
      'session_issued_at',
      'status',
      'token_hash',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.manual_patient_commands': {
    insertColumns: [
      'command_id',
      'command_kind',
      'created_at',
      'organization_id',
      'platform_user_id',
      'request_fingerprint',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgManualPatientCommand.ts:61',
    ],
  },
  'public.material_ratings': {
    insertColumns: [
      'id',
      'organization_id',
      'stars',
      'target_id',
      'target_kind',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.media_files': {
    insertColumns: [
      'available_qualities_json',
      'created_at',
      'delete_attempts',
      'delete_claim_token',
      'display_name',
      'folder_id',
      'hls_artifact_prefix',
      'hls_master_playlist_s3_key',
      'hosted_video_source_url',
      'id',
      'mime_type',
      'next_attempt_at',
      'organization_id',
      'original_name',
      'owner_kind',
      'poster_s3_key',
      'preview_attempts',
      'preview_md_key',
      'preview_next_attempt_at',
      'preview_sm_key',
      'preview_status',
      's3_key',
      'size_bytes',
      'source_height',
      'source_width',
      'standard_rendition_at',
      'status',
      'stored_path',
      'uploaded_by',
      'usage_purpose',
      'video_duration_seconds',
      'video_processing_error',
      'video_processing_status',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgLfkExercises.ts:213',
      'apps/webapp/src/infra/repos/pgPatientFiles.ts:127',
      'apps/webapp/src/infra/repos/pgPatientFiles.ts:306',
      'apps/webapp/src/infra/repos/s3MediaStorage.ts:138',
      'apps/webapp/src/infra/repos/s3MediaStorage.ts:630',
      'apps/webapp/src/infra/repos/s3MediaStorage.ts:681',
    ],
  },
  'public.media_folders': {
    insertColumns: [
      'created_at',
      'created_by',
      'id',
      'kind',
      'name',
      'organization_id',
      'parent_id',
      'patient_user_id',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/mediaFoldersRepo.ts:89',
      'apps/webapp/src/infra/repos/pgClientMediaFolders.ts:110',
      'apps/webapp/src/infra/repos/pgClientMediaFolders.ts:161',
    ],
  },
  'public.media_hls_proxy_error_events': {
    insertColumns: [
      'artifact_kind',
      'created_at',
      'http_status',
      'id',
      'media_id',
      'object_suffix',
      'organization_id',
      'reason_code',
      'user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/app-layer/media/hlsProxyErrorEvents.ts:38',
    ],
  },
  'public.media_playback_client_events': {
    insertColumns: [
      'created_at',
      'delivery',
      'error_detail',
      'event_class',
      'id',
      'media_id',
      'organization_id',
      'user_agent',
      'user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/app-layer/media/playbackClientEvents.ts:78',
    ],
  },
  'public.media_playback_resolution_events': {
    insertColumns: [
      'delivery',
      'id',
      'media_id',
      'organization_id',
      'resolved_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.media_playback_stats_hourly': {
    insertColumns: [
      'bucket_hour',
      'delivery',
      'organization_id',
      'resolved_count',
    ],
    directInsertCallsites: [],
  },
  'public.media_playback_user_video_first_resolve': {
    insertColumns: [
      'first_resolved_at',
      'media_id',
      'organization_id',
      'user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlaybackUserVideoFirstResolve.ts:23',
    ],
  },
  'public.media_transcode_jobs': {
    insertColumns: [
      'attempts',
      'created_at',
      'finished_at',
      'id',
      'last_error',
      'locked_at',
      'locked_by',
      'media_id',
      'next_attempt_at',
      'organization_id',
      'processing_started_at',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.media_upload_sessions': {
    insertColumns: [
      'aborted_at',
      'completed_at',
      'created_at',
      'expected_size_bytes',
      'expires_at',
      'id',
      'last_error',
      'media_id',
      'mime_type',
      'organization_id',
      'owner_user_id',
      'part_size_bytes',
      's3_key',
      'status',
      'updated_at',
      'upload_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/mediaUploadSessionsRepo.ts:57',
    ],
  },
  'public.message_drafts': {
    insertColumns: [
      'created_at',
      'draft_text_current',
      'external_chat_id',
      'external_message_id',
      'id',
      'identity_id',
      'source',
      'state',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.message_log': {
    insertColumns: [
      'category',
      'channel_bindings_used',
      'error_message',
      'id',
      'organization_id',
      'outcome',
      'platform_user_id',
      'sender_id',
      'sent_at',
      'text',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.motivational_quotes': {
    insertColumns: [
      'archived_at',
      'author',
      'body_text',
      'created_at',
      'id',
      'is_active',
      'organization_id',
      'sort_order',
    ],
    directInsertCallsites: [],
  },
  'public.notification_delivery_attempts': {
    insertColumns: [
      'channel',
      'created_at',
      'endpoint_hash',
      'error_message',
      'event_id',
      'id',
      'intent_type',
      'metadata',
      'occurrence_id',
      'organization_id',
      'provider_status_code',
      'reason',
      'recipient_ref',
      'status',
      'topic_code',
      'user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgNotificationDeliveryAttempts.ts:48',
    ],
  },
  'public.online_intake_answers': {
    insertColumns: [
      'created_at',
      'id',
      'ordinal',
      'organization_id',
      'question_id',
      'request_id',
      'value',
    ],
    directInsertCallsites: [],
  },
  'public.online_intake_attachments': {
    insertColumns: [
      'attachment_type',
      'created_at',
      'id',
      'mime_type',
      'organization_id',
      'original_name',
      'request_id',
      's3_key',
      'size_bytes',
      'url',
    ],
    directInsertCallsites: [],
  },
  'public.online_intake_requests': {
    insertColumns: [
      'created_at',
      'id',
      'organization_id',
      'status',
      'summary',
      'type',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.online_intake_status_history': {
    insertColumns: [
      'changed_at',
      'changed_by',
      'from_status',
      'id',
      'note',
      'organization_id',
      'request_id',
      'to_status',
    ],
    directInsertCallsites: [],
  },
  'public.operator_health_alert_sent': {
    insertColumns: [
      'dedup_key',
      'id',
      'sent_at',
      'severity',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgOperatorHealthAlertSent.ts:26',
    ],
  },
  'public.operator_health_failure_archive': {
    insertColumns: [
      'archived_at',
      'archived_by_user_id',
      'doctor_user_id',
      'health_probe',
      'id',
      'organization_id',
      'raw_error_truncated',
      'severity_at_archive',
      'source_id',
      'source_kind',
      'summary_json',
    ],
    directInsertCallsites: [],
  },
  'public.operator_incidents': {
    insertColumns: [
      'acknowledged_at',
      'alert_claim_phase',
      'alert_claim_token',
      'alert_claimed_at',
      'alert_sent_at',
      'dedup_key',
      'direction',
      'error_class',
      'error_detail',
      'id',
      'initial_alert_sent_at',
      'integration',
      'last_seen_at',
      'occurrence_count',
      'one_hour_alert_sent_at',
      'opened_at',
      'resolved_at',
    ],
    directInsertCallsites: [],
  },
  'public.operator_job_status': {
    insertColumns: [
      'job_family',
      'job_key',
      'last_duration_ms',
      'last_error',
      'last_failure_at',
      'last_finished_at',
      'last_started_at',
      'last_status',
      'last_success_at',
      'meta_json',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgOperatorHealthWrite.ts:48',
      'apps/webapp/src/infra/repos/pgOperatorHealthWrite.ts:95',
    ],
  },
  'public.org_brand_revisions': {
    insertColumns: [
      'accent_token',
      'archived_at',
      'archived_by_platform_user_id',
      'created_at',
      'created_by_platform_user_id',
      'display_name',
      'id',
      'logo_media_id',
      'organization_id',
      'patient_app_name',
      'published_at',
      'published_by_platform_user_id',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.org_enrollments': {
    insertColumns: [
      'created_at',
      'id',
      'organization_id',
      'platform_user_id',
      'portal_activated_at',
      'portal_activated_via',
      'status',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientOrganizationEnrollment.ts:76',
    ],
  },
  'public.organization_member_invites': {
    insertColumns: [
      'accepted_at',
      'accepted_by_platform_user_id',
      'accepted_membership_id',
      'created_at',
      'created_by_platform_user_id',
      'expires_at',
      'id',
      'invited_email',
      'invited_role',
      'organization_id',
      'status',
      'token_hash',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgOrganizationInvites.ts:182',
    ],
  },
  'public.organization_slug_claims': {
    insertColumns: [
      'created_at',
      'created_by_platform_user_id',
      'id',
      'kind',
      'organization_id',
      'slug',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgClinicDirectory.ts:216',
      'apps/webapp/src/infra/repos/pgClinicDirectory.ts:371',
    ],
  },
  'public.organization_slug_rename_events': {
    insertColumns: [
      'actor_platform_user_id',
      'created_at',
      'id',
      'initiated_by',
      'next_slug',
      'organization_id',
      'previous_slug',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgClinicDirectory.ts:379',
    ],
  },
  'public.outgoing_delivery_queue': {
    insertColumns: [
      'attempt_count',
      'channel',
      'created_at',
      'dead_at',
      'event_id',
      'failure_class',
      'id',
      'kind',
      'last_attempt_at',
      'last_error',
      'max_attempts',
      'next_retry_at',
      'organization_id',
      'payload_json',
      'priority',
      'reclaim_count',
      'sent_at',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgDoctorBroadcastDelivery.ts:64',
    ],
  },
  'public.password_altcha_challenges': {
    insertColumns: [
      'challenge_digest',
      'challenge_id',
      'consumed_at',
      'created_at',
      'expires_at',
      'identifier_key',
      'purpose',
    ],
    directInsertCallsites: [],
  },
  'public.password_login_identifier_protection': {
    insertColumns: [
      'failed_attempts',
      'identifier_key',
      'leased_user_id',
      'locked_until',
      'next_allowed_at',
      'updated_at',
      'verification_lease_token',
      'verification_lease_until',
    ],
    directInsertCallsites: [],
  },
  'public.patient_bookings': {
    insertColumns: [
      'booking_type',
      'branch_id',
      'branch_service_id',
      'branch_title_snapshot',
      'cancel_reason',
      'cancelled_at',
      'canonical_appointment_id',
      'category',
      'city',
      'city_code_snapshot',
      'contact_email',
      'contact_name',
      'contact_phone',
      'created_at',
      'duration_minutes_snapshot',
      'gcal_event_id',
      'id',
      'organization_id',
      'platform_user_id',
      'price_minor_snapshot',
      'provenance_created_by',
      'provenance_updated_by',
      'reminder_24h_sent',
      'reminder_2h_sent',
      'service_id',
      'service_title_snapshot',
      'slot_end',
      'slot_start',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.patient_comorbidity': {
    insertColumns: [
      'created_at',
      'created_by',
      'id',
      'organization_id',
      'patient_user_id',
      'removed_at',
      'since',
      'status',
      'text',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientComorbidities.ts:81',
    ],
  },
  'public.patient_content_rating_feedback': {
    insertColumns: [
      'comment',
      'content_page_id',
      'created_at',
      'id',
      'organization_id',
      'rating_value',
      'reason_codes',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.patient_daily_warmup_presentations': {
    insertColumns: [
      'content_page_id',
      'last_rotation_at',
      'organization_id',
      'skip_next_scheduled_rotation',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.patient_daily_warmup_video_views': {
    insertColumns: [
      'content_page_id',
      'id',
      'organization_id',
      'user_id',
      'viewed_at',
    ],
    directInsertCallsites: [],
  },
  'public.patient_diary_day_snapshots': {
    insertColumns: [
      'captured_at',
      'iana',
      'local_date',
      'organization_id',
      'plan_done_mask',
      'plan_instance_id',
      'plan_item_ids',
      'platform_user_id',
      'warmup_all_done',
      'warmup_done_count',
      'warmup_slot_limit',
    ],
    directInsertCallsites: [],
  },
  'public.patient_files': {
    insertColumns: [
      'category',
      'created_at',
      'file_name',
      'id',
      'media_file_id',
      'mime_type',
      'organization_id',
      'patient_user_id',
      's3_bucket',
      's3_key',
      'size_bytes',
      'uploaded_by_user_id',
      'visit_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientFiles.ts:145',
    ],
  },
  'public.patient_home_block_items': {
    insertColumns: [
      'badge_label',
      'block_code',
      'created_at',
      'id',
      'image_url_override',
      'is_visible',
      'organization_id',
      'show_title',
      'sort_order',
      'subtitle_override',
      'target_ref',
      'target_type',
      'title_override',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientHomeBlocks.ts:102',
    ],
  },
  'public.patient_home_blocks': {
    insertColumns: [
      'code',
      'created_at',
      'description',
      'icon_image_url',
      'is_visible',
      'organization_id',
      'sort_order',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.patient_invites': {
    insertColumns: [
      'accepted_at',
      'accepted_by_platform_user_id',
      'accepted_via',
      'bearer_exchanged_at',
      'continuation_expires_at',
      'continuation_hash',
      'created_at',
      'created_by_platform_user_id',
      'delivery_channel_hint',
      'enrollment_id',
      'expires_at',
      'id',
      'invited_email_normalized',
      'organization_id',
      'patient_user_id',
      'proof_attempts',
      'proof_code_hash',
      'proof_email_normalized',
      'proof_expires_at',
      'proof_started_at',
      'proof_verified_at',
      'recipient_binding',
      'revoked_at',
      'revoked_by_platform_user_id',
      'status',
      'superseded_by_invite_id',
      'token_hash',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientInvites.ts:211',
    ],
  },
  'public.patient_lfk_assignments': {
    insertColumns: [
      'assigned_at',
      'assigned_by',
      'complex_id',
      'id',
      'is_active',
      'organization_id',
      'patient_user_id',
      'template_id',
    ],
    directInsertCallsites: [],
  },
  'public.patient_merge_candidates': {
    insertColumns: [
      'anchor_user_id',
      'candidate_user_id',
      'created_at',
      'id',
      'organization_id',
      'payload',
      'reason',
      'resolved_at',
      'resolved_by',
      'status',
      'trigger_appointment_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientMergeCandidate.ts:44',
    ],
  },
  'public.patient_payment': {
    insertColumns: [
      'amount_minor',
      'appointment_id',
      'comment',
      'created_at',
      'created_by',
      'currency',
      'id',
      'idempotency_key',
      'kind',
      'organization_id',
      'patient_package_id',
      'patient_user_id',
      'provider',
      'provider_payment_id',
      'service',
      'status',
      'visit_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientPayments.ts:138',
      'apps/webapp/src/infra/repos/pgPatientPayments.ts:230',
    ],
  },
  'public.patient_practice_completions': {
    insertColumns: [
      'completed_at',
      'content_page_id',
      'feeling',
      'id',
      'notes',
      'organization_id',
      'source',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.patient_specialist_links': {
    insertColumns: [
      'created_at',
      'created_via',
      'ended_at',
      'ended_reason',
      'id',
      'organization_id',
      'patient_user_id',
      'source_link_id',
      'specialist_id',
      'status',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPatientVisibilityLinks.ts:15',
    ],
  },
  'public.phone_challenges': {
    insertColumns: [
      'challenge_id',
      'channel_context',
      'code',
      'created_at',
      'expires_at',
      'phone',
      'verify_attempts',
    ],
    directInsertCallsites: [],
  },
  'public.phone_messenger_bind_secrets': {
    insertColumns: [
      'challenge_id',
      'channel_code',
      'claimed_at',
      'claimed_external_id',
      'consumed_at',
      'created_at',
      'expires_at',
      'failure_code',
      'id',
      'phone_normalized',
      'purpose',
      'status',
      'token_hash',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.phone_otp_locks': {
    insertColumns: [
      'locked_until',
      'phone_normalized',
    ],
    directInsertCallsites: [],
  },
  'public.platform_user_contacts': {
    insertColumns: [
      'contact_type',
      'created_at',
      'id',
      'organization_id',
      'platform_user_id',
      'source',
      'updated_at',
      'value',
      'value_normalized',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformUserContacts.ts:109',
    ],
  },
  'public.platform_users': {
    insertColumns: [
      'blocked_at',
      'blocked_by',
      'blocked_reason',
      'calendar_timezone',
      'created_at',
      'display_name',
      'first_name',
      'id',
      'is_archived',
      'is_blocked',
      'last_name',
      'merged_at',
      'merged_into_id',
      'patronymic',
      'reminder_muted_until',
      'role',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgDoctorClientCreate.ts:175',
      'apps/webapp/src/infra/repos/pgDoctorClientCreate.ts:77',
      'apps/webapp/src/infra/repos/pgOAuthUserResolve.ts:125',
    ],
  },
  'public.product_analytics_events_recent': {
    insertColumns: [
      'client_session_id',
      'entry_channel',
      'event_type',
      'id',
      'metadata',
      'occurred_at',
      'organization_id',
      'page_key',
      'push_kind',
      'push_tracking_id',
      'topic_code',
      'user_id',
      'warmup_slogan_key',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgProductAnalytics.ts:133',
    ],
  },
  'public.product_analytics_hourly': {
    insertColumns: [
      'bucket_hour',
      'entry_channel',
      'event_count',
      'event_type',
      'organization_id',
      'page_key',
      'push_kind',
      'topic_code',
      'updated_at',
      'warmup_slogan_key',
    ],
    directInsertCallsites: [],
  },
  'public.product_analytics_user_hourly': {
    insertColumns: [
      'active_minutes',
      'app_opens',
      'bucket_hour',
      'entry_channel',
      'last_seen_at',
      'organization_id',
      'page_key',
      'page_views',
      'push_opens',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.product_push_notifications': {
    insertColumns: [
      'created_at',
      'id',
      'intent_type',
      'occurrence_id',
      'open_url',
      'organization_id',
      'push_kind',
      'title',
      'topic_code',
      'user_id',
      'warmup_slogan_key',
      'warmup_slogan_text',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgProductAnalytics.ts:243',
    ],
  },
  'public.program_action_log': {
    insertColumns: [
      'action_type',
      'created_at',
      'id',
      'instance_id',
      'instance_stage_item_id',
      'note',
      'organization_id',
      'patient_user_id',
      'payload',
      'session_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgProgramActionLog.ts:157',
    ],
  },
  'public.program_item_discussion_messages': {
    insertColumns: [
      'body',
      'created_at',
      'id',
      'instance_stage_item_id',
      'media_file_id',
      'organization_id',
      'origin',
      'patient_user_id',
      'sender_role',
      'support_message_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgProgramItemDiscussion.ts:279',
    ],
  },
  'public.program_item_discussion_reads': {
    insertColumns: [
      'instance_stage_item_id',
      'last_read_at',
      'organization_id',
      'patient_user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgProgramItemDiscussion.ts:587',
    ],
  },
  'public.question_messages': {
    insertColumns: [
      'created_at',
      'id',
      'message_text',
      'question_id',
      'sender_type',
    ],
    directInsertCallsites: [],
  },
  'public.recommendation_regions': {
    insertColumns: [
      'body_region_id',
      'organization_id',
      'recommendation_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgRecommendations.ts:426',
      'apps/webapp/src/infra/repos/pgRecommendations.ts:497',
    ],
  },
  'public.recommendations': {
    insertColumns: [
      'body_md',
      'body_region_id',
      'created_at',
      'created_by',
      'domain',
      'duration_text',
      'frequency_text',
      'id',
      'is_archived',
      'media',
      'organization_id',
      'quantity_text',
      'tags',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgRecommendations.ts:408',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:957',
    ],
  },
  'public.reference_catalog_baselines': {
    insertColumns: [
      'created_at',
      'definition_json',
      'version',
    ],
    directInsertCallsites: [],
  },
  'public.reference_catalog_snapshot_receipts': {
    insertColumns: [
      'baseline_version',
      'organization_id',
      'seeded_at',
    ],
    directInsertCallsites: [],
  },
  'public.reference_categories': {
    insertColumns: [
      'code',
      'created_at',
      'id',
      'is_user_extensible',
      'organization_id',
      'owner_id',
      'tenant_id',
      'title',
    ],
    directInsertCallsites: [],
  },
  'public.reference_items': {
    insertColumns: [
      'category_id',
      'code',
      'created_at',
      'deleted_at',
      'id',
      'is_active',
      'meta_json',
      'organization_id',
      'sort_order',
      'title',
    ],
    directInsertCallsites: [],
  },
  'public.reminder_occurrence_history': {
    insertColumns: [
      'category',
      'created_at',
      'delivery_channel',
      'delivery_generation',
      'delivery_job_id',
      'done_at',
      'error_code',
      'failed_at',
      'id',
      'integrator_occurrence_id',
      'integrator_rule_id',
      'occurred_at',
      'occurrence_key',
      'organization_id',
      'planned_at',
      'platform_user_id',
      'queued_at',
      'seen_at',
      'sent_at',
      'skip_reason',
      'skipped_at',
      'snoozed_at',
      'snoozed_until',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.reminder_rules': {
    insertColumns: [
      'category',
      'content_mode',
      'created_at',
      'custom_text',
      'custom_title',
      'days_mask',
      'display_description',
      'display_title',
      'id',
      'integrator_rule_id',
      'interval_minutes',
      'is_enabled',
      'linked_object_id',
      'linked_object_type',
      'notification_topic_code',
      'organization_id',
      'platform_user_id',
      'quiet_hours_end_minute',
      'quiet_hours_start_minute',
      'reminder_intent',
      'schedule_data',
      'schedule_type',
      'timezone',
      'updated_at',
      'window_end_minute',
      'window_start_minute',
    ],
    directInsertCallsites: [],
  },
  'public.saas_billing_accounts': {
    insertColumns: [
      'billing_address',
      'billing_email',
      'billing_requisites',
      'created_at',
      'id',
      'legal_name',
      'organization_id',
      'registration_reason_code',
      'tax_identifier',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:379',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:513',
    ],
  },
  'public.saas_billing_invoices': {
    insertColumns: [
      'additional_seat_quantity',
      'amount_minor',
      'carried_debt_minor',
      'created_at',
      'currency',
      'description',
      'expires_at',
      'id',
      'invoice_kind',
      'organization_id',
      'paid_at',
      'provider_checkout_url',
      'provider_id',
      'provider_idempotency_key',
      'provider_invoice_ref',
      'saas_billing_account_id',
      'saas_billing_subscription_id',
      'service_period_ends_at',
      'service_period_starts_at',
      'status',
      'superseded_by_invoice_id',
      'tariff_billing_period',
      'tariff_id',
      'tariff_name',
      'tariff_snapshot',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:141',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:2016',
    ],
  },
  'public.saas_billing_periods': {
    insertColumns: [
      'code',
      'created_at',
      'is_selectable',
      'label',
      'months',
      'sort_order',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:574',
    ],
  },
  'public.saas_billing_provider_events': {
    insertColumns: [
      'created_at',
      'event_type',
      'id',
      'organization_id',
      'processed_at',
      'provider_event_id',
      'provider_id',
      'raw_payload',
      'saas_billing_invoice_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:1359',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:1379',
    ],
  },
  'public.saas_billing_refunds': {
    insertColumns: [
      'amount_minor',
      'confirmed_at',
      'created_at',
      'currency',
      'id',
      'organization_id',
      'provider_id',
      'provider_idempotency_key',
      'provider_refund_ref',
      'saas_billing_invoice_id',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.saas_billing_subscriptions': {
    insertColumns: [
      'autopay_consent_text',
      'autopay_consented_at',
      'autopay_revoked_at',
      'billing_period_code',
      'cancelled_at',
      'created_at',
      'current_period_ends_at',
      'current_period_starts_at',
      'grace_ends_at',
      'id',
      'lifecycle_state',
      'organization_id',
      'paid_additional_seats',
      'pending_billing_period_code',
      'pending_tariff_id',
      'provider_id',
      'read_only_ends_at',
      'saas_billing_account_id',
      'saved_payment_method_id',
      'source',
      'status',
      'tariff_id',
      'tariff_snapshot',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:1011',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:1844',
    ],
  },
  'public.saas_isolation_coverage_runs': {
    insertColumns: [
      'checks_count',
      'created_at',
      'finished_at',
      'id',
      'services_checked',
      'started_at',
      'status',
      'unexpected_errors_count',
    ],
    directInsertCallsites: [],
  },
  'public.saas_isolation_event_hourly': {
    insertColumns: [
      'bucket_start',
      'event_id',
      'occurrence_count',
    ],
    directInsertCallsites: [],
  },
  'public.saas_isolation_events': {
    insertColumns: [
      'event_class',
      'explanation_status',
      'fingerprint',
      'first_seen_at',
      'id',
      'last_seen_at',
      'lifecycle_status',
      'occurrence_count',
      'resolved_at',
      'source_operation',
      'source_service',
    ],
    directInsertCallsites: [],
  },
  'public.saas_org_entitlement_overrides': {
    insertColumns: [
      'created_at',
      'enabled',
      'expires_at',
      'id',
      'mechanic',
      'organization_id',
      'quota',
      'seat_limit_override',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:802',
    ],
  },
  'public.saas_organization_trials': {
    insertColumns: [
      'created_at',
      'created_by',
      'discount_ends_at',
      'ends_at',
      'id',
      'organization_id',
      'post_trial_behavior',
      'post_trial_tariff_id',
      'started_at',
      'status',
      'tariff_id',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:338',
      'apps/webapp/src/infra/repos/pgSaasBilling.ts:890',
    ],
  },
  'public.saas_paid_period_policy': {
    insertColumns: [
      'created_at',
      'is_active',
      'key',
      'post_paid_period_behavior',
      'post_paid_period_tariff_id',
      'updated_at',
      'updated_by',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:909',
    ],
  },
  'public.saas_registration_tariff_policy': {
    insertColumns: [
      'created_at',
      'key',
      'tariff_id',
      'updated_at',
      'updated_by',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:945',
    ],
  },
  'public.saas_tariff_period_prices': {
    insertColumns: [
      'billing_period_code',
      'created_at',
      'discounted_price_minor',
      'price_minor',
      'tariff_id',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:249',
    ],
  },
  'public.saas_tariffs': {
    insertColumns: [
      'additional_seat_price_minor',
      'billing_period',
      'created_at',
      'currency',
      'description',
      'discounted_price_minor',
      'downgrade_policies',
      'id',
      'included_seats',
      'is_active',
      'mailing_templates',
      'mechanic_access_policies',
      'mechanics',
      'name',
      'price_minor',
      'quotas',
      'system_access_policy',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:686',
    ],
  },
  'public.saas_trial_policy': {
    insertColumns: [
      'created_at',
      'discount_window_days',
      'duration_days',
      'is_active',
      'key',
      'post_trial_behavior',
      'post_trial_tariff_id',
      'start_event',
      'updated_at',
      'updated_by',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgPlatformEntitlements.ts:867',
    ],
  },
  'public.specialist_signup_intents': {
    insertColumns: [
      'challenge_id',
      'created_at',
      'email_normalized',
      'id',
      'organization_slug',
      'organization_title',
      'provisioned_at',
      'provisioned_membership_id',
      'provisioned_organization_id',
      'provisioned_specialist_id',
      'specialist_full_name',
      'status',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.specialist_tasks': {
    insertColumns: [
      'completed_at',
      'created_at',
      'description',
      'due_at',
      'due_has_time',
      'id',
      'is_important',
      'organization_id',
      'owner_user_id',
      'patient_user_id',
      'remind_at',
      'reminder_sent_at',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgSpecialistTasks.ts:105',
    ],
  },
  'public.staff_security_profiles': {
    insertColumns: [
      'created_at',
      'factor_type',
      'factor_verified_at',
      'failed_attempts',
      'locked_until',
      'login_challenge_expires_at',
      'login_challenge_hash',
      'pending_totp_secret_ciphertext',
      'recovery_code_hashes',
      'recovery_codes_confirmed_at',
      'replacement_required',
      'session_version',
      'totp_secret_ciphertext',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.support_conversation_messages': {
    insertColumns: [
      'conversation_id',
      'created_at',
      'delivered_at',
      'delivery_status',
      'external_chat_id',
      'external_message_id',
      'id',
      'integrator_message_id',
      'media_type',
      'media_url',
      'message_type',
      'organization_id',
      'read_at',
      'sender_role',
      'source',
      'text',
    ],
    directInsertCallsites: [],
  },
  'public.support_conversations': {
    insertColumns: [
      'admin_scope',
      'channel_code',
      'channel_external_id',
      'close_reason',
      'closed_at',
      'created_at',
      'id',
      'integrator_conversation_id',
      'last_message_at',
      'opened_at',
      'organization_id',
      'pending_message_drafts',
      'platform_user_id',
      'source',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.support_question_messages': {
    insertColumns: [
      'created_at',
      'id',
      'integrator_question_message_id',
      'organization_id',
      'question_id',
      'sender_role',
      'text',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgIntegratorSupportQuestionOwnership.ts:74',
    ],
  },
  'public.support_questions': {
    insertColumns: [
      'answered_at',
      'conversation_id',
      'created_at',
      'id',
      'integrator_question_id',
      'organization_id',
      'status',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgIntegratorSupportQuestionOwnership.ts:35',
    ],
  },
  'public.symptom_entries': {
    insertColumns: [
      'created_at',
      'entry_type',
      'id',
      'notes',
      'organization_id',
      'patient_practice_completion_id',
      'platform_user_id',
      'recorded_at',
      'source',
      'tracking_id',
      'user_id',
      'value_0_10',
    ],
    directInsertCallsites: [],
  },
  'public.symptom_trackings': {
    insertColumns: [
      'created_at',
      'deleted_at',
      'diagnosis_ref_id',
      'diagnosis_text',
      'id',
      'is_active',
      'organization_id',
      'platform_user_id',
      'region_ref_id',
      'side',
      'stage_ref_id',
      'symptom_key',
      'symptom_title',
      'symptom_type_ref_id',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.system_settings': {
    insertColumns: [
      'key',
      'organization_id',
      'scope',
      'updated_at',
      'updated_by',
      'value_json',
    ],
    directInsertCallsites: [],
  },
  'public.telegram_users': {
    insertColumns: [
      'created_at',
      'first_name',
      'id',
      'is_active',
      'last_name',
      'last_start_at',
      'last_update_id',
      'notify_msk',
      'notify_online',
      'notify_spb',
      'phone',
      'state',
      'telegram_id',
      'updated_at',
      'username',
    ],
    directInsertCallsites: [],
  },
  'public.test_attempts': {
    insertColumns: [
      'accepted_at',
      'accepted_by',
      'id',
      'instance_stage_item_id',
      'organization_id',
      'patient_user_id',
      'started_at',
      'submitted_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramTestAttempts.ts:197',
      'apps/webapp/src/infra/repos/pgTreatmentProgramTestAttempts.ts:372',
    ],
  },
  'public.test_results': {
    insertColumns: [
      'attempt_id',
      'created_at',
      'decided_by',
      'id',
      'normalized_decision',
      'organization_id',
      'raw_value',
      'test_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramTestAttempts.ts:443',
    ],
  },
  'public.test_set_items': {
    insertColumns: [
      'comment',
      'id',
      'organization_id',
      'sort_order',
      'test_id',
      'test_set_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTestSets.ts:528',
    ],
  },
  'public.test_sets': {
    insertColumns: [
      'created_at',
      'created_by',
      'description',
      'id',
      'is_archived',
      'organization_id',
      'publication_status',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTestSets.ts:378',
    ],
  },
  'public.tests': {
    insertColumns: [
      'assessment_kind',
      'body_region_id',
      'created_at',
      'created_by',
      'description',
      'id',
      'is_archived',
      'media',
      'organization_id',
      'raw_text',
      'scoring',
      'tags',
      'test_type',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgClinicalTests.ts:447',
    ],
  },
  'public.treatment_program_events': {
    insertColumns: [
      'actor_id',
      'created_at',
      'event_type',
      'id',
      'instance_id',
      'organization_id',
      'payload',
      'reason',
      'target_id',
      'target_type',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramEvents.ts:121',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:1588',
    ],
  },
  'public.treatment_program_instance_stage_groups': {
    insertColumns: [
      'description',
      'id',
      'organization_id',
      'schedule_text',
      'sort_order',
      'source_group_id',
      'stage_id',
      'system_kind',
      'title',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:1745',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:323',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:858',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:868',
    ],
  },
  'public.treatment_program_instance_stage_items': {
    insertColumns: [
      'comment',
      'completed_at',
      'created_at',
      'group_id',
      'id',
      'is_actionable',
      'item_ref_id',
      'item_type',
      'last_viewed_at',
      'local_comment',
      'organization_id',
      'settings',
      'snapshot',
      'sort_order',
      'stage_id',
      'status',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:1184',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:1339',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:1457',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:367',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:915',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:984',
    ],
  },
  'public.treatment_program_instance_stages': {
    insertColumns: [
      'description',
      'expected_duration_days',
      'expected_duration_text',
      'goals',
      'id',
      'instance_id',
      'local_comment',
      'objectives',
      'organization_id',
      'skip_reason',
      'sort_order',
      'source_stage_id',
      'started_at',
      'status',
      'title',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:281',
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:837',
    ],
  },
  'public.treatment_program_instances': {
    insertColumns: [
      'assigned_by',
      'assignment_source',
      'created_at',
      'id',
      'organization_id',
      'patient_plan_last_opened_at',
      'patient_user_id',
      'status',
      'template_id',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgramInstance.ts:264',
    ],
  },
  'public.treatment_program_template_stage_groups': {
    insertColumns: [
      'description',
      'id',
      'organization_id',
      'schedule_text',
      'sort_order',
      'stage_id',
      'system_kind',
      'title',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:1211',
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:1705',
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:394',
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:405',
    ],
  },
  'public.treatment_program_template_stage_items': {
    insertColumns: [
      'comment',
      'group_id',
      'id',
      'item_ref_id',
      'item_type',
      'organization_id',
      'settings',
      'sort_order',
      'stage_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:1013',
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:1767',
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:1891',
    ],
  },
  'public.treatment_program_template_stages': {
    insertColumns: [
      'description',
      'expected_duration_days',
      'expected_duration_text',
      'goals',
      'id',
      'objectives',
      'organization_id',
      'sort_order',
      'template_id',
      'title',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:582',
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:821',
    ],
  },
  'public.treatment_program_templates': {
    insertColumns: [
      'created_at',
      'created_by',
      'description',
      'id',
      'organization_id',
      'status',
      'title',
      'updated_at',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTreatmentProgram.ts:571',
    ],
  },
  'public.user_channel_bindings': {
    insertColumns: [
      'bot_blocked_at',
      'bot_blocked_reason',
      'channel_code',
      'created_at',
      'display_handle',
      'external_id',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.user_channel_preferences': {
    insertColumns: [
      'channel_code',
      'created_at',
      'id',
      'is_enabled_for_messages',
      'is_enabled_for_notifications',
      'is_preferred_for_auth',
      'platform_user_id',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.user_contacts': {
    insertColumns: [
      'confirmed_at',
      'contact_kind',
      'created_at',
      'id',
      'is_primary',
      'platform_user_id',
      'source_origin',
      'updated_at',
      'value_normalized',
    ],
    directInsertCallsites: [],
  },
  'public.user_identity': {
    insertColumns: [
      'birth_date',
      'created_at',
      'display_name',
      'first_name',
      'last_name',
      'patronymic',
      'platform_user_id',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.user_notification_topic_channels': {
    insertColumns: [
      'channel_code',
      'is_enabled',
      'topic_code',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgTopicChannelPrefs.ts:50',
    ],
  },
  'public.user_notification_topics': {
    insertColumns: [
      'is_enabled',
      'topic_code',
      'updated_at',
      'user_id',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgUserProjection.ts:158',
    ],
  },
  'public.user_oauth_bindings': {
    insertColumns: [
      'created_at',
      'email',
      'id',
      'provider',
      'provider_user_id',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.user_passkey_accounts': {
    insertColumns: [
      'created_at',
      'user_handle',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.user_passkey_challenges': {
    insertColumns: [
      'challenge',
      'consumed_at',
      'created_at',
      'expected_origin',
      'expires_at',
      'id',
      'purpose',
      'rp_id',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.user_passkey_credentials': {
    insertColumns: [
      'backed_up',
      'counter',
      'created_at',
      'credential_id',
      'device_type',
      'last_used_at',
      'public_key',
      'transports',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.user_password_credentials': {
    insertColumns: [
      'algo',
      'failed_attempts',
      'locked_until',
      'next_allowed_at',
      'password_hash',
      'updated_at',
      'user_id',
      'verification_lease_token',
      'verification_lease_until',
    ],
    directInsertCallsites: [],
  },
  'public.user_phone_history': {
    insertColumns: [
      'confirming_channel',
      'id',
      'organization_id',
      'phone_normalized',
      'platform_user_id',
      'source',
      'valid_from',
      'valid_to',
    ],
    directInsertCallsites: [
      'apps/webapp/src/infra/repos/pgDoctorClientCreate.ts:188',
    ],
  },
  'public.user_questions': {
    insertColumns: [
      'answered',
      'answered_at',
      'conversation_id',
      'created_at',
      'id',
      'telegram_message_id',
      'text',
      'user_identity_id',
    ],
    directInsertCallsites: [],
  },
  'public.user_web_push_subscriptions': {
    insertColumns: [
      'auth',
      'created_at',
      'endpoint',
      'id',
      'p256dh',
      'updated_at',
      'user_agent',
      'user_id',
    ],
    directInsertCallsites: [],
  },
  'public.users': {
    insertColumns: [
      'created_at',
      'id',
      'merged_into_user_id',
      'updated_at',
    ],
    directInsertCallsites: [],
  },
  'public.webapp_schema_migrations': {
    insertColumns: [
      'applied_at',
      'filename',
    ],
    directInsertCallsites: [],
  },
};
