ALTER TABLE "public"."admin_audit_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."admin_audit_log" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."admin_audit_log";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."admin_audit_log" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_appointment_cancellations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_appointment_cancellations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_cancellations";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_cancellations" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_appointment_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_appointment_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_appointment_history_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_appointment_history_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_history_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_history_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_appointment_no_shows" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_appointment_no_shows" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_no_shows";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_no_shows" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_appointment_reschedules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_appointment_reschedules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_reschedules";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_reschedules" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_appointment_staff_comments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_appointment_staff_comments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_staff_comments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_staff_comments" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_appointments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_appointments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointments" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_availability_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_availability_rules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_availability_rules";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_availability_rules" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_booking_form_fields" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_booking_form_fields" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_booking_form_fields";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_booking_form_fields" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_booking_form_submissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_booking_form_submissions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_booking_form_submissions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_booking_form_submissions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_branches" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_branches" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_branches";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_branches" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_cancellation_policies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_cancellation_policies" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_cancellation_policies";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_cancellation_policies" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_clinic_services" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_clinic_services" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_clinic_services";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_clinic_services" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_external_entity_mappings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_external_entity_mappings" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_external_entity_mappings";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_external_entity_mappings" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_package_history_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_package_history_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_package_history_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_package_history_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_package_usages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_package_usages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_package_usages";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_package_usages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_patient_booking_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_patient_booking_profiles" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_patient_booking_profiles";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_patient_booking_profiles" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_patient_packages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_patient_packages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_patient_packages";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_patient_packages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_patient_timeline_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_patient_timeline_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_patient_timeline_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_patient_timeline_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_payment_history_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_payment_history_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_payment_history_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_payment_history_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_payment_intents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_payment_intents" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_payment_intents";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_payment_intents" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_payment_provider_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_payment_provider_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_payment_provider_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_payment_provider_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_payments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_payments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_payments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_payments" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_prepayment_policies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_prepayment_policies" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_prepayment_policies";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_prepayment_policies" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_product_history_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_product_history_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_product_history_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_product_history_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_product_pay_links" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_product_pay_links" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_product_pay_links";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_product_pay_links" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_product_purchases" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_product_purchases" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_product_purchases";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_product_purchases" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_products" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_products" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_products";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_products" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_refunds" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_refunds" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_refunds";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_refunds" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_reschedule_policies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_reschedule_policies" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_reschedule_policies";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_reschedule_policies" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_rooms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_rooms" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_rooms";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_rooms" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_schedule_blocks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_schedule_blocks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_schedule_blocks";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_schedule_blocks" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_schedule_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_schedule_templates" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_schedule_templates";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_schedule_templates" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_service_location_availability" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_service_location_availability" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_service_location_availability";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_service_location_availability" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_specialist_locations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_specialist_locations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_specialist_locations";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_specialist_locations" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_specialist_rooms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_specialist_rooms" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_specialist_rooms";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_specialist_rooms" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_specialist_service_availability" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_specialist_service_availability" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_specialist_service_availability";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_specialist_service_availability" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_specialists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_specialists" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_specialists";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_specialists" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_subscription_packages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_subscription_packages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_subscription_packages";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_subscription_packages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_working_days" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_working_days" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_working_days";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_working_days" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."be_working_hours" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_working_hours" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_working_hours";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_working_hours" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."broadcast_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."broadcast_audit" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."broadcast_audit";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."broadcast_audit" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_anamnesis_illness" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_anamnesis_illness" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_illness";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_illness" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_anamnesis_lifestyle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_anamnesis_lifestyle" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_lifestyle";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_lifestyle" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_anamnesis_trauma" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_anamnesis_trauma" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_trauma";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_trauma" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_complaint" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_complaint" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_complaint";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_complaint" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_diagnosis" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_diagnosis" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_diagnosis";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_diagnosis" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_diagnosis_catalog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_diagnosis_catalog" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_diagnosis_catalog";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_diagnosis_catalog" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_test_regions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_test_regions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_test_regions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_test_regions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_visit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_visit" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_visit";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_visit" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."content_access_grants_webapp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_access_grants_webapp" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."content_access_grants_webapp";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."content_access_grants_webapp" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."content_pages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_pages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."content_pages";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."content_pages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."content_sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_sections" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."content_sections";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."content_sections" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."courses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."courses" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."courses";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."courses" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."doctor_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."doctor_notes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."doctor_notes";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."doctor_notes" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."doctor_patient_support" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."doctor_patient_support" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."doctor_patient_support";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."doctor_patient_support" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."lfk_complex_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lfk_complex_templates" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."lfk_complex_templates";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."lfk_complex_templates" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."lfk_complexes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lfk_complexes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."lfk_complexes";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."lfk_complexes" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."lfk_exercise_regions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lfk_exercise_regions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."lfk_exercise_regions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."lfk_exercise_regions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."lfk_exercises" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lfk_exercises" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."lfk_exercises";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."lfk_exercises" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."lfk_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lfk_sessions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."lfk_sessions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."lfk_sessions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."mailing_logs_webapp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."mailing_logs_webapp" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."mailing_logs_webapp";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."mailing_logs_webapp" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."material_ratings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."material_ratings" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."material_ratings";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."material_ratings" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."media_files" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."media_files" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_files";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_files" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."media_folders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."media_folders" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_folders";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_folders" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."media_hls_proxy_error_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."media_hls_proxy_error_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_hls_proxy_error_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_hls_proxy_error_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."media_playback_client_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."media_playback_client_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_playback_client_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_playback_client_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."media_playback_resolution_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."media_playback_resolution_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_playback_resolution_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_playback_resolution_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."media_playback_user_video_first_resolve" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."media_playback_user_video_first_resolve" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_playback_user_video_first_resolve";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_playback_user_video_first_resolve" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."media_upload_sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."media_upload_sessions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_upload_sessions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_upload_sessions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."message_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."message_log" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."message_log";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."message_log" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."motivational_quotes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."motivational_quotes" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."motivational_quotes";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."motivational_quotes" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."online_intake_requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."online_intake_requests" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."online_intake_requests";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."online_intake_requests" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."operator_health_failure_archive" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."operator_health_failure_archive" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."operator_health_failure_archive";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."operator_health_failure_archive" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_comorbidity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_comorbidity" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_comorbidity";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_comorbidity" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_content_rating_feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_content_rating_feedback" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_content_rating_feedback";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_content_rating_feedback" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_daily_warmup_presentations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_daily_warmup_presentations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_daily_warmup_presentations";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_daily_warmup_presentations" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_diary_day_snapshots" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_diary_day_snapshots" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_diary_day_snapshots";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_diary_day_snapshots" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_files" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_files" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_files";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_files" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_home_blocks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_home_blocks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_home_blocks";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_home_blocks" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_lfk_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_lfk_assignments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_lfk_assignments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_lfk_assignments" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_merge_candidates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_merge_candidates" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_merge_candidates";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_merge_candidates" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_payment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_payment";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_payment" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_practice_completions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_practice_completions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_practice_completions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_practice_completions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."product_analytics_events_recent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."product_analytics_events_recent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."product_analytics_events_recent";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."product_analytics_events_recent" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."product_analytics_user_hourly" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."product_analytics_user_hourly" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."product_analytics_user_hourly";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."product_analytics_user_hourly" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."product_push_notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."product_push_notifications" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."product_push_notifications";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."product_push_notifications" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."recommendation_regions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."recommendation_regions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."recommendation_regions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."recommendation_regions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."recommendations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."recommendations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."recommendations";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."recommendations" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."reference_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reference_categories" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."reference_categories";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."reference_categories" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."reminder_journal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reminder_journal" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."reminder_journal";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."reminder_journal" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."reminder_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reminder_rules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."reminder_rules";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."reminder_rules" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."specialist_tasks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."specialist_tasks" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."specialist_tasks";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."specialist_tasks" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."support_conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."support_conversations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."support_conversations";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."support_conversations" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."support_questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."support_questions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."support_questions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."support_questions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."symptom_trackings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."symptom_trackings" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."symptom_trackings";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."symptom_trackings" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."test_attempts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."test_attempts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."test_attempts";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."test_attempts" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."test_sets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."test_sets" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."test_sets";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."test_sets" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."tests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tests" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."tests";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."tests" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_instances" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_instances" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."treatment_program_instances";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."treatment_program_instances" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_templates" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."treatment_program_templates";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."treatment_program_templates" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."user_subscriptions_webapp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."user_subscriptions_webapp" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."user_subscriptions_webapp";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."user_subscriptions_webapp" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
