ALTER TABLE "public"."be_package_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_package_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."be_package_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."be_package_items" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR (EXISTS ( SELECT 1 FROM "public"."be_subscription_packages" AS "p0_8_4_parent" WHERE "p0_8_4_parent"."id" = "package_id" AND "p0_8_4_parent"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ) AND EXISTS ( SELECT 1 FROM "public"."be_clinic_services" AS "p0_8_4_cross" WHERE "p0_8_4_cross"."id" = "service_id" AND "p0_8_4_cross"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid )))) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR (EXISTS ( SELECT 1 FROM "public"."be_subscription_packages" AS "p0_8_4_parent" WHERE "p0_8_4_parent"."id" = "package_id" AND "p0_8_4_parent"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ) AND EXISTS ( SELECT 1 FROM "public"."be_clinic_services" AS "p0_8_4_cross" WHERE "p0_8_4_cross"."id" = "service_id" AND "p0_8_4_cross"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ))));
ALTER TABLE "public"."be_patient_package_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."be_patient_package_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."be_patient_package_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."be_patient_package_items" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR (EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "p0_8_4_parent" WHERE "p0_8_4_parent"."id" = "patient_package_id" AND "p0_8_4_parent"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ) AND EXISTS ( SELECT 1 FROM "public"."be_clinic_services" AS "p0_8_4_cross" WHERE "p0_8_4_cross"."id" = "service_id" AND "p0_8_4_cross"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid )))) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR (EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "p0_8_4_parent" WHERE "p0_8_4_parent"."id" = "patient_package_id" AND "p0_8_4_parent"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ) AND EXISTS ( SELECT 1 FROM "public"."be_clinic_services" AS "p0_8_4_cross" WHERE "p0_8_4_cross"."id" = "service_id" AND "p0_8_4_cross"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ))));
ALTER TABLE "public"."broadcast_audit_recipients" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."broadcast_audit_recipients" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."broadcast_audit_recipients";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."broadcast_audit_recipients" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_complaint_update" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_complaint_update" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."clinical_complaint_update";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."clinical_complaint_update" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_diagnosis_status_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_diagnosis_status_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."clinical_diagnosis_status_history";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."clinical_diagnosis_status_history" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."clinical_diagnosis_update" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."clinical_diagnosis_update" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."clinical_diagnosis_update";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."clinical_diagnosis_update" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."content_section_slug_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."content_section_slug_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."content_section_slug_history";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."content_section_slug_history" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."lfk_complex_exercises" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lfk_complex_exercises" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."lfk_complex_exercises";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."lfk_complex_exercises" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."lfk_complex_template_exercises" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lfk_complex_template_exercises" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."lfk_complex_template_exercises";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."lfk_complex_template_exercises" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."lfk_exercise_media" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."lfk_exercise_media" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."lfk_exercise_media";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."lfk_exercise_media" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."media_transcode_jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."media_transcode_jobs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."media_transcode_jobs";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."media_transcode_jobs" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."notification_delivery_attempts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."notification_delivery_attempts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."notification_delivery_attempts";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."notification_delivery_attempts" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."online_intake_answers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."online_intake_answers" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."online_intake_answers";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."online_intake_answers" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."online_intake_attachments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."online_intake_attachments" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."online_intake_attachments";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."online_intake_attachments" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."online_intake_status_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."online_intake_status_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."online_intake_status_history";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."online_intake_status_history" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_daily_warmup_video_views" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_daily_warmup_video_views" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."patient_daily_warmup_video_views";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."patient_daily_warmup_video_views" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."patient_home_block_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."patient_home_block_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."patient_home_block_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."patient_home_block_items" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."program_action_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."program_action_log" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."program_action_log";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."program_action_log" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."program_item_discussion_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."program_item_discussion_messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."program_item_discussion_messages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."program_item_discussion_messages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."program_item_discussion_reads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."program_item_discussion_reads" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."program_item_discussion_reads";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."program_item_discussion_reads" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."reference_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reference_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."reference_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."reference_items" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."reminder_delivery_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reminder_delivery_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."reminder_delivery_events";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."reminder_delivery_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."reminder_occurrence_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."reminder_occurrence_history" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."reminder_occurrence_history";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."reminder_occurrence_history" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."support_conversation_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."support_conversation_messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."support_conversation_messages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."support_conversation_messages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."support_delivery_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."support_delivery_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."support_delivery_events";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."support_delivery_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."support_question_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."support_question_messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."support_question_messages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."support_question_messages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."symptom_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."symptom_entries" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."symptom_entries";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."symptom_entries" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."test_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."test_results" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."test_results";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."test_results" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."test_set_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."test_set_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."test_set_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."test_set_items" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_events" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_events";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_events" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_instance_stage_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_instance_stage_groups" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stage_groups";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stage_groups" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_instance_stage_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_instance_stage_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stage_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stage_items" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_instance_stages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_instance_stages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_template_stage_groups" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_template_stage_groups" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_template_stage_groups";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_template_stage_groups" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_template_stage_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_template_stage_items" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_template_stage_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_template_stage_items" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."treatment_program_template_stages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."treatment_program_template_stages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_template_stages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_template_stages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "public"."webapp_reminder_occurrences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."webapp_reminder_occurrences" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."webapp_reminder_occurrences";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."webapp_reminder_occurrences" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
