ALTER TABLE "integrator"."contacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."contacts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."contacts";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."contacts" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."content_access_grants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."content_access_grants" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."content_access_grants";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."content_access_grants" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."conversation_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."conversation_messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."conversation_messages";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."conversation_messages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."conversations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."conversations" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."conversations";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."conversations" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."mailing_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."mailing_logs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."mailing_logs";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."mailing_logs" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."mailings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."mailings" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."mailings";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."mailings" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."message_drafts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."message_drafts" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."message_drafts";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."message_drafts" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."question_messages" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."question_messages" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."question_messages";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."question_messages" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."user_questions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."user_questions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_questions";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_questions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."user_reminder_delivery_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."user_reminder_delivery_logs" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_delivery_logs";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_delivery_logs" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."user_reminder_occurrences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."user_reminder_occurrences" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_occurrences";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_occurrences" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."user_reminder_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."user_reminder_rules" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_rules";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_rules" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
ALTER TABLE "integrator"."user_subscriptions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "integrator"."user_subscriptions" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_subscriptions";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_subscriptions" FOR ALL USING ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid)) WITH CHECK ((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid));
