-- 0169: B4-core patient wall — fail-closed staff-or-patient branch on top of the existing
-- dormant-permissive org predicate, for the 60 patient-owned SCOPED tables identified in
-- docs/_TODO/SAAS_FOUNDATION/LOG.md (taskdb #653, R2_ENFORCEMENT_PREP_PLAN.md B4-core).
--
-- Owner decision 2026-07-11: staff/doctor visibility stays ORG-WIDE (variant A — no assignment
-- predicate; a staff session sets app.actor='staff' and is unaffected by anything below). The
-- patient wall is ABSOLUTE: a patient session sees ONLY rows it owns; unset/empty context denies
-- (fail-closed) for the patient branch specifically, even though the surrounding org predicate
-- stays dormant-permissive (unset app.org still permits — unchanged from 0160-0168).
--
-- IDENTITY GUC (P0.13/T0.4 convention, aligned taskdb #656 — see smoke-p0-13-db-isolation.mjs):
-- a webapp patient session sets app.patient_user_id (uuid, platform_users.id); an integrator
-- patient session sets the DEDICATED app.integrator_user_id (bigint, integrator.users.id). The
-- 9 bigint-cast targets below (mailing_logs_webapp, user_subscriptions_webapp,
-- reminder_delivery_events, reminder_occurrence_history, integrator.contacts,
-- integrator.content_access_grants, integrator.mailing_logs, integrator.user_reminder_rules,
-- integrator.user_subscriptions) compare against app.integrator_user_id — NOT app.patient_user_id
-- cast to bigint, which is what this file originally (incorrectly) emitted; corrected in place
-- here since this migration has never been applied outside disposable scratch-DB smokes.
--
-- Every block below is the EXACT generated output of (same policy names/targets as 0160-0162,
-- now carrying descriptor.patientColumn — see rls-descriptor-model.mjs `patientOwnedColumns`):
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-3-policy-targets.mjs --sql   (44 of these targets)
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-4-policy-targets.mjs --sql   (11 of these targets)
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-5-policy-targets.mjs --sql   (5 of these targets)
-- filtered to only the tables that now declare a patientColumn (the other targets in those three
-- families are unchanged and NOT re-emitted here — see 0160/0161/0162 for their policies).
--
-- Idempotent: ENABLE RLS is a no-op if already set; DROP POLICY IF EXISTS +
-- CREATE POLICY replaces the prior (org-only) policy of the same name in place.
--
-- Rollback (ops): re-run the pre-B4-core generator output for these same 60 tables/policy names
-- to restore the org-only predicate, i.e. re-apply the exact CREATE POLICY statements from
-- 0160/0161/0162 for these specific tables (git show 757d17d48:apps/webapp/db/drizzle-migrations/0160_p0_8_3_public_direct_org_rls.sql
-- etc., or `git log -p` on this file's previous commit) — DROP POLICY IF EXISTS + CREATE POLICY
-- with the plain org predicate. No column/table drop, no data change; safe to revert at any time.
--
-- Dormant in prod today: the app DB role still has BYPASSRLS (P0.5/B5 not flipped), so RLS does
-- not apply to any current traffic regardless of this predicate change. This migration only
-- changes what the policy WOULD do under a NOBYPASSRLS role — proven via the B6 real-policy
-- smoke (docs/_TODO/SAAS_FOUNDATION/scripts/smoke-r2-real-policy-isolation.mjs), scratch DB only.

ALTER TABLE "public"."be_appointment_staff_comments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_staff_comments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_staff_comments" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."be_appointments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointments" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."be_patient_booking_profiles" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_patient_booking_profiles";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_patient_booking_profiles" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."be_patient_packages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_patient_packages";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_patient_packages" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."be_patient_timeline_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_patient_timeline_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_patient_timeline_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."be_payment_history_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_payment_history_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_payment_history_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."be_payment_intents" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_payment_intents";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_payment_intents" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."be_payments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_payments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_payments" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."be_product_purchases" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_product_purchases";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_product_purchases" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."clinical_anamnesis_illness" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_illness";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_illness" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."clinical_anamnesis_lifestyle" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_lifestyle";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_lifestyle" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."clinical_anamnesis_trauma" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_trauma";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_anamnesis_trauma" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."clinical_complaint" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_complaint";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_complaint" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."clinical_diagnosis" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_diagnosis";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_diagnosis" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."clinical_visit" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."clinical_visit";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."clinical_visit" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."content_access_grants_webapp" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."content_access_grants_webapp";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."content_access_grants_webapp" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."doctor_notes" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."doctor_notes";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."doctor_notes" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."doctor_patient_support" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."doctor_patient_support";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."doctor_patient_support" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."lfk_complexes" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."lfk_complexes";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."lfk_complexes" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."lfk_sessions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."lfk_sessions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."lfk_sessions" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."mailing_logs_webapp" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."mailing_logs_webapp";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."mailing_logs_webapp" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "integrator_user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "integrator_user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
ALTER TABLE "public"."material_ratings" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."material_ratings";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."material_ratings" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."media_folders" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_folders";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_folders" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND ("patient_user_id" IS NULL OR (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND ("patient_user_id" IS NULL OR (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))));
ALTER TABLE "public"."message_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."message_log";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."message_log" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."online_intake_requests" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."online_intake_requests";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."online_intake_requests" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."org_enrollments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."org_enrollments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."org_enrollments" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_comorbidity" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_comorbidity";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_comorbidity" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_content_rating_feedback" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_content_rating_feedback";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_content_rating_feedback" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_daily_warmup_presentations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_daily_warmup_presentations";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_daily_warmup_presentations" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_diary_day_snapshots" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_diary_day_snapshots";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_diary_day_snapshots" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_files" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_files";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_files" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_lfk_assignments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_lfk_assignments";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_lfk_assignments" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_payment" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_payment";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_payment" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_practice_completions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."patient_practice_completions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."patient_practice_completions" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."product_analytics_events_recent" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."product_analytics_events_recent";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."product_analytics_events_recent" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."product_analytics_user_hourly" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."product_analytics_user_hourly";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."product_analytics_user_hourly" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."product_push_notifications" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."product_push_notifications";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."product_push_notifications" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."reminder_rules" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."reminder_rules";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."reminder_rules" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."specialist_tasks" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."specialist_tasks";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."specialist_tasks" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."support_conversations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."support_conversations";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."support_conversations" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."symptom_trackings" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."symptom_trackings";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."symptom_trackings" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."test_attempts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."test_attempts";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."test_attempts" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."treatment_program_instances" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."treatment_program_instances";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."treatment_program_instances" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."user_subscriptions_webapp" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."user_subscriptions_webapp";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."user_subscriptions_webapp" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "integrator_user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "integrator_user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
ALTER TABLE "public"."be_patient_package_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."be_patient_package_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."be_patient_package_items" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR (EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "p0_8_4_parent" WHERE "p0_8_4_parent"."id" = "patient_package_id" AND "p0_8_4_parent"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ) AND EXISTS ( SELECT 1 FROM "public"."be_clinic_services" AS "p0_8_4_cross" WHERE "p0_8_4_cross"."id" = "service_id" AND "p0_8_4_cross"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ))) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "p0_8_4_patient_parent" WHERE "p0_8_4_patient_parent"."id" = "patient_package_id" AND "p0_8_4_patient_parent"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR (EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "p0_8_4_parent" WHERE "p0_8_4_parent"."id" = "patient_package_id" AND "p0_8_4_parent"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ) AND EXISTS ( SELECT 1 FROM "public"."be_clinic_services" AS "p0_8_4_cross" WHERE "p0_8_4_cross"."id" = "service_id" AND "p0_8_4_cross"."organization_id" = NULLIF(current_setting('app.org', true), '')::uuid ))) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "p0_8_4_patient_parent" WHERE "p0_8_4_patient_parent"."id" = "patient_package_id" AND "p0_8_4_patient_parent"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."broadcast_audit_recipients" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."broadcast_audit_recipients";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."broadcast_audit_recipients" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."notification_delivery_attempts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."notification_delivery_attempts";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."notification_delivery_attempts" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."patient_daily_warmup_video_views" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."patient_daily_warmup_video_views";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."patient_daily_warmup_video_views" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."program_action_log" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."program_action_log";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."program_action_log" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."program_item_discussion_messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."program_item_discussion_messages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."program_item_discussion_messages" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."program_item_discussion_reads" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."program_item_discussion_reads";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."program_item_discussion_reads" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."reminder_delivery_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."reminder_delivery_events";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."reminder_delivery_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "integrator_user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "integrator_user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
ALTER TABLE "public"."reminder_occurrence_history" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."reminder_occurrence_history";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."reminder_occurrence_history" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "integrator_user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "integrator_user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
ALTER TABLE "public"."symptom_entries" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."symptom_entries";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."symptom_entries" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."webapp_reminder_occurrences" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."webapp_reminder_occurrences";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."webapp_reminder_occurrences" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "integrator"."contacts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."contacts";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."contacts" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
ALTER TABLE "integrator"."content_access_grants" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."content_access_grants";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."content_access_grants" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
ALTER TABLE "integrator"."mailing_logs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."mailing_logs";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."mailing_logs" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
ALTER TABLE "integrator"."user_reminder_rules" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_rules";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_rules" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
ALTER TABLE "integrator"."user_subscriptions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_subscriptions";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_subscriptions" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint))));
