-- 0170: B4-fanout gap closure — chain-only patient wall (docs/_TODO/SAAS_FOUNDATION/
-- R2_ENFORCEMENT_PREP_PLAN.md, taskdb #656). Closes the "chain-only" gap left open by 0169
-- (B4-core): 11 SCOPED tables that have NO direct patient-owner column, but whose owning patient
-- IS reachable by walking one or more FK hops to a table that does carry one. Same fail-closed
-- staff-or-patient shape as 0169, except the patient branch is an EXISTS chain of INNER JOINs
-- instead of a plain column match — see rls-descriptor-model.mjs `patientChainOwnedTables` and
-- rls-sql-renderer.mjs `renderPatientChainPredicate`. A NULL/broken hop anywhere in the chain
-- fails the join and denies for a patient session (fail-closed); staff (app.actor='staff') is
-- unaffected (org-wide, variant A, unchanged from 0160-0169).
--
-- Targets (11):
--   P0.8.3 (public., direct_org_column, 1 table):
--     public.support_questions
--       -> EXISTS support_conversations WHERE id = conversation_id AND platform_user_id = :guc
--   P0.8.4 (public., denorm_org_column, 3 tables):
--     public.support_conversation_messages -> support_conversations.platform_user_id (1 hop)
--     public.support_question_messages     -> support_questions -> support_conversations (2 hops)
--     public.support_delivery_events        -> support_conversation_messages -> support_conversations (2 hops)
--   P0.8.5 (integrator., 7 tables):
--     I2 identity-bridge (direct_org_column, 1 hop through integrator.identities):
--       integrator.conversations, integrator.message_drafts, integrator.user_questions
--     I3 parent-denorm (denorm_org_column):
--       integrator.conversation_messages -> conversations -> identities (2 hops)
--       integrator.question_messages     -> user_questions -> identities (2 hops)
--       integrator.user_reminder_occurrences   -> user_reminder_rules (1 hop, direct bigint user_id)
--       integrator.user_reminder_delivery_logs  -> user_reminder_occurrences -> user_reminder_rules (2 hops)
--
-- All integrator chain terminals compare against the DEDICATED `app.integrator_user_id` GUC
-- (bigint) per the P0.13/T0.4 convention (see smoke-p0-13-db-isolation.mjs); the public.support_*
-- chain terminals compare against `app.patient_user_id` (uuid) — same column already registered
-- DIRECTLY on public.support_conversations in 0169 (patientOwnedColumns), not a new identity space.
--
-- Every block below is the EXACT generated output of (same policy names as 0160-0162/0169):
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-3-policy-targets.mjs --sql   (1 of these targets)
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-4-policy-targets.mjs --sql   (3 of these targets)
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-5-policy-targets.mjs --sql   (7 of these targets)
-- filtered to only the tables that now declare a patientChain (all other targets in those three
-- families are unchanged and NOT re-emitted here — see 0160/0161/0162/0169 for their policies).
--
-- Idempotent: ENABLE RLS is a no-op if already set; DROP POLICY IF EXISTS +
-- CREATE POLICY replaces the prior (org-only) policy of the same name in place.
--
-- Rollback (ops): DROP POLICY IF EXISTS + re-CREATE the plain org-only predicate for these same 11
-- tables/policy names (git show <this file's previous commit> for the pre-0170 CREATE POLICY
-- statements, or re-run p0-8-{3,4,5}-policy-targets.mjs --sql from a commit before taskdb #656).
-- No column/table drop, no data change; safe to revert at any time.
--
-- Dormant in prod today: the app DB role still has BYPASSRLS (P0.5/B5 not flipped), so RLS does
-- not apply to any current traffic regardless of this predicate change. This migration only
-- changes what the policy WOULD do under a NOBYPASSRLS role — proven via the extended B6
-- real-policy smoke (docs/_TODO/SAAS_FOUNDATION/scripts/smoke-r2-real-policy-isolation.mjs),
-- scratch DB only.

ALTER TABLE "public"."support_questions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."support_questions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."support_questions" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."support_conversations" AS "b4f_conv" WHERE "b4f_conv"."id" = "conversation_id" AND "b4f_conv"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."support_conversations" AS "b4f_conv" WHERE "b4f_conv"."id" = "conversation_id" AND "b4f_conv"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."support_conversation_messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."support_conversation_messages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."support_conversation_messages" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."support_conversations" AS "b4f_conv" WHERE "b4f_conv"."id" = "conversation_id" AND "b4f_conv"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."support_conversations" AS "b4f_conv" WHERE "b4f_conv"."id" = "conversation_id" AND "b4f_conv"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."support_delivery_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."support_delivery_events";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."support_delivery_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."support_conversation_messages" AS "b4f_msg" JOIN "public"."support_conversations" AS "b4f_conv" ON "b4f_conv"."id" = "b4f_msg"."conversation_id" WHERE "b4f_msg"."id" = "conversation_message_id" AND "b4f_conv"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."support_conversation_messages" AS "b4f_msg" JOIN "public"."support_conversations" AS "b4f_conv" ON "b4f_conv"."id" = "b4f_msg"."conversation_id" WHERE "b4f_msg"."id" = "conversation_message_id" AND "b4f_conv"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."support_question_messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."support_question_messages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."support_question_messages" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."support_questions" AS "b4f_question" JOIN "public"."support_conversations" AS "b4f_conv" ON "b4f_conv"."id" = "b4f_question"."conversation_id" WHERE "b4f_question"."id" = "question_id" AND "b4f_conv"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."support_questions" AS "b4f_question" JOIN "public"."support_conversations" AS "b4f_conv" ON "b4f_conv"."id" = "b4f_question"."conversation_id" WHERE "b4f_question"."id" = "question_id" AND "b4f_conv"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "integrator"."conversation_messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."conversation_messages";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."conversation_messages" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."conversations" AS "b4f_conv" JOIN "integrator"."identities" AS "b4f_ident" ON "b4f_ident"."id" = "b4f_conv"."user_identity_id" WHERE "b4f_conv"."id" = "conversation_id" AND "b4f_ident"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."conversations" AS "b4f_conv" JOIN "integrator"."identities" AS "b4f_ident" ON "b4f_ident"."id" = "b4f_conv"."user_identity_id" WHERE "b4f_conv"."id" = "conversation_id" AND "b4f_ident"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint )))));
ALTER TABLE "integrator"."conversations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."conversations";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."conversations" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."identities" AS "b4f_conversations_identity" WHERE "b4f_conversations_identity"."id" = "user_identity_id" AND "b4f_conversations_identity"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."identities" AS "b4f_conversations_identity" WHERE "b4f_conversations_identity"."id" = "user_identity_id" AND "b4f_conversations_identity"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint )))));
ALTER TABLE "integrator"."message_drafts" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."message_drafts";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."message_drafts" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."identities" AS "b4f_message_drafts_identity" WHERE "b4f_message_drafts_identity"."id" = "identity_id" AND "b4f_message_drafts_identity"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."identities" AS "b4f_message_drafts_identity" WHERE "b4f_message_drafts_identity"."id" = "identity_id" AND "b4f_message_drafts_identity"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint )))));
ALTER TABLE "integrator"."question_messages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."question_messages";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."question_messages" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."user_questions" AS "b4f_question" JOIN "integrator"."identities" AS "b4f_ident" ON "b4f_ident"."id" = "b4f_question"."user_identity_id" WHERE "b4f_question"."id" = "question_id" AND "b4f_ident"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."user_questions" AS "b4f_question" JOIN "integrator"."identities" AS "b4f_ident" ON "b4f_ident"."id" = "b4f_question"."user_identity_id" WHERE "b4f_question"."id" = "question_id" AND "b4f_ident"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint )))));
ALTER TABLE "integrator"."user_questions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_questions";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_questions" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."identities" AS "b4f_user_questions_identity" WHERE "b4f_user_questions_identity"."id" = "user_identity_id" AND "b4f_user_questions_identity"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."identities" AS "b4f_user_questions_identity" WHERE "b4f_user_questions_identity"."id" = "user_identity_id" AND "b4f_user_questions_identity"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint )))));
ALTER TABLE "integrator"."user_reminder_delivery_logs" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_delivery_logs";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_delivery_logs" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."user_reminder_occurrences" AS "b4f_occ" JOIN "integrator"."user_reminder_rules" AS "b4f_rule" ON "b4f_rule"."id" = "b4f_occ"."rule_id" WHERE "b4f_occ"."id" = "occurrence_id" AND "b4f_rule"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."user_reminder_occurrences" AS "b4f_occ" JOIN "integrator"."user_reminder_rules" AS "b4f_rule" ON "b4f_rule"."id" = "b4f_occ"."rule_id" WHERE "b4f_occ"."id" = "occurrence_id" AND "b4f_rule"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint )))));
ALTER TABLE "integrator"."user_reminder_occurrences" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_occurrences";
CREATE POLICY "saas_org_dormant_p0_8_5" ON "integrator"."user_reminder_occurrences" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."user_reminder_rules" AS "b4f_rule" WHERE "b4f_rule"."id" = "rule_id" AND "b4f_rule"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.integrator_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "integrator"."user_reminder_rules" AS "b4f_rule" WHERE "b4f_rule"."id" = "rule_id" AND "b4f_rule"."user_id" = NULLIF(current_setting('app.integrator_user_id', true), '')::bigint )))));
