-- 0171: B4-core-3 — close the 9 MORE patient-owned chain tables the B4-core-2 audit found still
-- org-only (docs/_TODO/SAAS_FOUNDATION/LOG.md, taskdb #658). Same P0.8.4 (public., denorm_org_column)
-- family and same fail-closed staff-or-patient shape as 0169 (B4-core) / 0170 (B4-fanout), except
-- each of these 9 is a SINGLE-hop parent_denorm child whose immediate FK parent already carries a
-- direct patient-owner column (registered in 0169's patientOwnedColumns) — see
-- rls-descriptor-model.mjs `patientChainOwnedTables` (B4-core-3 block) and
-- rls-sql-renderer.mjs `renderPatientChainPredicate`. A NULL/broken hop denies for a patient
-- session (fail-closed); staff (app.actor='staff') is unaffected (org-wide, variant A, unchanged).
--
-- Targets (9), all P0.8.4 (public., denorm_org_column):
--   public.online_intake_answers        -> EXISTS online_intake_requests WHERE id = request_id AND user_id = :guc
--   public.online_intake_attachments     -> EXISTS online_intake_requests WHERE id = request_id AND user_id = :guc
--   public.online_intake_status_history  -> EXISTS online_intake_requests WHERE id = request_id AND user_id = :guc
--   public.clinical_complaint_update      -> EXISTS clinical_complaint WHERE id = complaint_id AND patient_user_id = :guc
--   public.clinical_diagnosis_update       -> EXISTS clinical_diagnosis WHERE id = diagnosis_id AND patient_user_id = :guc
--   public.clinical_diagnosis_status_history -> EXISTS clinical_diagnosis WHERE id = diagnosis_id AND patient_user_id = :guc
--   public.test_results                   -> EXISTS test_attempts WHERE id = attempt_id AND patient_user_id = :guc
--   public.treatment_program_instance_stages -> EXISTS treatment_program_instances WHERE id = instance_id AND patient_user_id = :guc
--   public.lfk_complex_exercises            -> EXISTS lfk_complexes WHERE id = complex_id AND platform_user_id = :guc
--
-- All 9 chain terminals compare against `app.patient_user_id` (uuid) — these are all webapp
-- platform_users.id chains, not integrator bigint identities.
--
-- Every block below is the EXACT generated output of (same policy name as 0160/0161/0170):
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-4-policy-targets.mjs --sql
-- filtered to only these 9 tables (all now declare a patientChain) — the other 28 targets in that
-- family are unchanged and NOT re-emitted here (see 0161/0170 for their policies).
--
-- Idempotent: ENABLE RLS is a no-op if already set; DROP POLICY IF EXISTS +
-- CREATE POLICY replaces the prior (org-only) policy of the same name in place.
--
-- Rollback (ops): DROP POLICY IF EXISTS + re-CREATE the plain org-only predicate for these same 9
-- tables/policy name (git show <this file's previous commit> for the pre-0171 CREATE POLICY
-- statements, or re-run p0-8-4-policy-targets.mjs --sql from a commit before taskdb #658).
-- No column/table drop, no data change; safe to revert at any time.
--
-- Dormant in prod today: the app DB role still has BYPASSRLS (P0.5/B5 not flipped), so RLS does
-- not apply to any current traffic regardless of this predicate change. This migration only
-- changes what the policy WOULD do under a NOBYPASSRLS role — proven via the extended real-policy
-- smoke (docs/_TODO/SAAS_FOUNDATION/scripts/smoke-r2-real-policy-isolation.mjs), scratch DB only.

ALTER TABLE "public"."online_intake_answers" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."online_intake_answers";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."online_intake_answers" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."online_intake_requests" AS "b4f_intake_request" WHERE "b4f_intake_request"."id" = "request_id" AND "b4f_intake_request"."user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."online_intake_requests" AS "b4f_intake_request" WHERE "b4f_intake_request"."id" = "request_id" AND "b4f_intake_request"."user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."online_intake_attachments" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."online_intake_attachments";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."online_intake_attachments" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."online_intake_requests" AS "b4f_intake_request" WHERE "b4f_intake_request"."id" = "request_id" AND "b4f_intake_request"."user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."online_intake_requests" AS "b4f_intake_request" WHERE "b4f_intake_request"."id" = "request_id" AND "b4f_intake_request"."user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."online_intake_status_history" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."online_intake_status_history";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."online_intake_status_history" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."online_intake_requests" AS "b4f_intake_request" WHERE "b4f_intake_request"."id" = "request_id" AND "b4f_intake_request"."user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."online_intake_requests" AS "b4f_intake_request" WHERE "b4f_intake_request"."id" = "request_id" AND "b4f_intake_request"."user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."clinical_complaint_update" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."clinical_complaint_update";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."clinical_complaint_update" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."clinical_complaint" AS "b4f_complaint" WHERE "b4f_complaint"."id" = "complaint_id" AND "b4f_complaint"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."clinical_complaint" AS "b4f_complaint" WHERE "b4f_complaint"."id" = "complaint_id" AND "b4f_complaint"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."clinical_diagnosis_update" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."clinical_diagnosis_update";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."clinical_diagnosis_update" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."clinical_diagnosis" AS "b4f_diagnosis" WHERE "b4f_diagnosis"."id" = "diagnosis_id" AND "b4f_diagnosis"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."clinical_diagnosis" AS "b4f_diagnosis" WHERE "b4f_diagnosis"."id" = "diagnosis_id" AND "b4f_diagnosis"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."clinical_diagnosis_status_history" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."clinical_diagnosis_status_history";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."clinical_diagnosis_status_history" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."clinical_diagnosis" AS "b4f_diagnosis" WHERE "b4f_diagnosis"."id" = "diagnosis_id" AND "b4f_diagnosis"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."clinical_diagnosis" AS "b4f_diagnosis" WHERE "b4f_diagnosis"."id" = "diagnosis_id" AND "b4f_diagnosis"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."test_results" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."test_results";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."test_results" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."test_attempts" AS "b4f_attempt" WHERE "b4f_attempt"."id" = "attempt_id" AND "b4f_attempt"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."test_attempts" AS "b4f_attempt" WHERE "b4f_attempt"."id" = "attempt_id" AND "b4f_attempt"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."treatment_program_instance_stages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stages";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stages" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."treatment_program_instances" AS "b4f_instance" WHERE "b4f_instance"."id" = "instance_id" AND "b4f_instance"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."treatment_program_instances" AS "b4f_instance" WHERE "b4f_instance"."id" = "instance_id" AND "b4f_instance"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."lfk_complex_exercises" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."lfk_complex_exercises";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."lfk_complex_exercises" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."lfk_complexes" AS "b4f_complex" WHERE "b4f_complex"."id" = "complex_id" AND "b4f_complex"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."lfk_complexes" AS "b4f_complex" WHERE "b4f_complex"."id" = "complex_id" AND "b4f_complex"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
