-- 0172: B4-core-3 exhaustive census follow-up (docs/_TODO/SAAS_FOUNDATION/LOG.md, taskdb #658).
-- 0171 closed the 9 tables named in the brief. The mandated exhaustive census that followed —
-- systematically checking every not-yet-walled SCOPED table's FK columns against the walled-table
-- set — found 18 MORE patient-owned tables still org-only: single/double-hop parent_denorm
-- chains to an already-walled patient-owning parent, or (4 of them) a direct `user_id` column that
-- had simply been missed. Same fail-closed staff-or-patient shape as 0169/0170/0171.
--
-- Targets (18):
--   P0.8.4 (public., denorm_org_column, 3 tables):
--     public.treatment_program_events -> treatment_program_instances.patient_user_id (instance_id, 1 hop)
--     public.treatment_program_instance_stage_items  -> treatment_program_instance_stages -> treatment_program_instances.patient_user_id (stage_id, instance_id; 2 hops — stages itself has no direct column)
--     public.treatment_program_instance_stage_groups -> same 2-hop chain (stage_id, instance_id)
--   P0.8.3 (public., direct_org_column, 15 tables):
--     chain-owned (11), each EXISTS to an already-walled parent:
--       be_appointment_cancellations/events/history_events/no_shows/reschedules,
--       be_booking_form_submissions -> be_appointments.platform_user_id (appointment_id, 1 hop)
--       be_refunds -> be_payments.platform_user_id (payment_id, 1 hop)
--       be_package_usages, be_package_history_events -> be_patient_packages.platform_user_id (patient_package_id, 1 hop)
--       be_product_history_events -> be_product_purchases.platform_user_id (product_purchase_id, 1 hop)
--       reminder_journal -> reminder_rules.platform_user_id (rule_id, 1 hop)
--     direct-column (4), a plain `user_id` column referencing platform_users(id) that had been missed
--     (same shape as the already-walled patient_daily_warmup_video_views/product_analytics_events_recent):
--       media_playback_client_events, media_hls_proxy_error_events,
--       media_playback_resolution_events, media_playback_user_video_first_resolve
--
-- All chain/direct terminals compare against `app.patient_user_id` (uuid) — these are all webapp
-- platform_users.id relationships, not integrator bigint identities.
--
-- Every block below is the EXACT generated output of (same policy names as 0160/0161/0169-0171):
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-3-policy-targets.mjs --sql   (15 of these targets)
--   node docs/_TODO/SAAS_FOUNDATION/scripts/p0-8-4-policy-targets.mjs --sql   (3 of these targets)
-- filtered to only these 18 tables (all now declare a patientColumn/patientChain) — the other
-- targets in those two families are unchanged and NOT re-emitted here (see 0160/0161/0169/0170/0171
-- for their policies).
--
-- Idempotent: ENABLE RLS is a no-op if already set; DROP POLICY IF EXISTS +
-- CREATE POLICY replaces the prior (org-only) policy of the same name in place.
--
-- Rollback (ops): DROP POLICY IF EXISTS + re-CREATE the plain org-only predicate for these same 18
-- tables/policy names (git show <this file's previous commit> for the pre-0172 CREATE POLICY
-- statements, or re-run p0-8-{3,4}-policy-targets.mjs --sql from a commit before taskdb #658's
-- census follow-up). No column/table drop, no data change; safe to revert at any time.
--
-- Dormant in prod today: the app DB role still has BYPASSRLS (P0.5/B5 not flipped), so RLS does
-- not apply to any current traffic regardless of this predicate change. This migration only
-- changes what the policy WOULD do under a NOBYPASSRLS role — proven via the extended real-policy
-- smoke (docs/_TODO/SAAS_FOUNDATION/scripts/smoke-r2-real-policy-isolation.mjs), scratch DB only.

ALTER TABLE "public"."be_appointment_cancellations" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_cancellations";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_cancellations" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_appointment_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_appointment_history_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_history_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_history_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_appointment_no_shows" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_no_shows";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_no_shows" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_appointment_reschedules" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_appointment_reschedules";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_appointment_reschedules" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_booking_form_submissions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_booking_form_submissions";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_booking_form_submissions" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_appointments" AS "b4f_appt" WHERE "b4f_appt"."id" = "appointment_id" AND "b4f_appt"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_package_history_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_package_history_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_package_history_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "b4f_pkg" WHERE "b4f_pkg"."id" = "patient_package_id" AND "b4f_pkg"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "b4f_pkg" WHERE "b4f_pkg"."id" = "patient_package_id" AND "b4f_pkg"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_package_usages" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_package_usages";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_package_usages" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "b4f_pkg" WHERE "b4f_pkg"."id" = "patient_package_id" AND "b4f_pkg"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_patient_packages" AS "b4f_pkg" WHERE "b4f_pkg"."id" = "patient_package_id" AND "b4f_pkg"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_product_history_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_product_history_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_product_history_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_product_purchases" AS "b4f_purchase" WHERE "b4f_purchase"."id" = "product_purchase_id" AND "b4f_purchase"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_product_purchases" AS "b4f_purchase" WHERE "b4f_purchase"."id" = "product_purchase_id" AND "b4f_purchase"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."be_refunds" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."be_refunds";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."be_refunds" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_payments" AS "b4f_payment" WHERE "b4f_payment"."id" = "payment_id" AND "b4f_payment"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."be_payments" AS "b4f_payment" WHERE "b4f_payment"."id" = "payment_id" AND "b4f_payment"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."reminder_journal" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."reminder_journal";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."reminder_journal" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."reminder_rules" AS "b4f_rule" WHERE "b4f_rule"."id" = "rule_id" AND "b4f_rule"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."reminder_rules" AS "b4f_rule" WHERE "b4f_rule"."id" = "rule_id" AND "b4f_rule"."platform_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."media_playback_client_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_playback_client_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_playback_client_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."media_hls_proxy_error_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_hls_proxy_error_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_hls_proxy_error_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."media_playback_resolution_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_playback_resolution_events";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_playback_resolution_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."media_playback_user_video_first_resolve" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_3" ON "public"."media_playback_user_video_first_resolve";
CREATE POLICY "saas_org_dormant_p0_8_3" ON "public"."media_playback_user_video_first_resolve" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid)))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND "user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid))));
ALTER TABLE "public"."treatment_program_events" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_events";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_events" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."treatment_program_instances" AS "b4f_instance" WHERE "b4f_instance"."id" = "instance_id" AND "b4f_instance"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."treatment_program_instances" AS "b4f_instance" WHERE "b4f_instance"."id" = "instance_id" AND "b4f_instance"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."treatment_program_instance_stage_items" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stage_items";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stage_items" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."treatment_program_instance_stages" AS "b4f_stage" JOIN "public"."treatment_program_instances" AS "b4f_instance" ON "b4f_instance"."id" = "b4f_stage"."instance_id" WHERE "b4f_stage"."id" = "stage_id" AND "b4f_instance"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."treatment_program_instance_stages" AS "b4f_stage" JOIN "public"."treatment_program_instances" AS "b4f_instance" ON "b4f_instance"."id" = "b4f_stage"."instance_id" WHERE "b4f_stage"."id" = "stage_id" AND "b4f_instance"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
ALTER TABLE "public"."treatment_program_instance_stage_groups" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stage_groups";
CREATE POLICY "saas_org_dormant_p0_8_4" ON "public"."treatment_program_instance_stage_groups" FOR ALL USING (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."treatment_program_instance_stages" AS "b4f_stage" JOIN "public"."treatment_program_instances" AS "b4f_instance" ON "b4f_instance"."id" = "b4f_stage"."instance_id" WHERE "b4f_stage"."id" = "stage_id" AND "b4f_instance"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid ))))) WITH CHECK (((NULLIF(current_setting('app.org', true), '') IS NULL OR "organization_id" = NULLIF(current_setting('app.org', true), '')::uuid) AND (NULLIF(current_setting('app.actor', true), '') = 'staff' OR (NULLIF(current_setting('app.patient_user_id', true), '') IS NOT NULL AND EXISTS ( SELECT 1 FROM "public"."treatment_program_instance_stages" AS "b4f_stage" JOIN "public"."treatment_program_instances" AS "b4f_instance" ON "b4f_instance"."id" = "b4f_stage"."instance_id" WHERE "b4f_stage"."id" = "stage_id" AND "b4f_instance"."patient_user_id" = NULLIF(current_setting('app.patient_user_id', true), '')::uuid )))));
