-- 0237_r7_drop_public_rubitime_mirror_tables: R7 archive-then-drop, DROP half.
--
-- Authority: docs/archive/2026-07-rubitime-retirement/SAAS_FOUNDATION/RUBITIME_RETIREMENT_R7_ARCHIVE_DROP_RUNBOOK.md §4 "Migration
-- Rules" -- "Generate a normal repo migration; do not run ad hoc DROP TABLE". This is that migration.
-- The completed retirement used the archive/verify procedure recorded under
-- docs/archive/2026-07-rubitime-retirement/. Its old one-shot is now inert archive evidence, not an
-- operator entrypoint (runbook §3 + DB_CLEANUP_SEQUENCE.md §Step 2).
--
-- SCOPE: exactly the two legacy public rubitime-mirror (public shadow) tables, and nothing else.
--   public.rubitime_records  -- DB_CLEANUP_SEQUENCE.md:178,209 (`archive_if_present`, listed under
--                               "Archive-before-drop tables"); R7_TABLE_DISPOSITION.md:49-50
--                               ("Archive Before Drop" ... "Nothing to archive/drop" on TEST because
--                               to_regclass returns NULL there); RUNBOOK.md:47.
--   public.rubitime_events   -- DB_CLEANUP_SEQUENCE.md:179,209; R7_TABLE_DISPOSITION.md:51; RUNBOOK.md:47.
--
-- These are the pre-SaaS public-schema Rubitime raw mirrors created by the original introspected
-- baseline (still present in apps/webapp/db/drizzle-migrations/meta/0000_snapshot.json ..
-- 0205_snapshot.json as `public.rubitime_records` / `public.rubitime_events`). They are absent from the
-- current TEST database, so this migration is a no-op there; they DO come back with any fresh pre-SaaS
-- prod dump (§2 of SAAS_PROD_DEPLOY_PROCESS.md restores the old prod DB), which is precisely why the
-- drop must exist as a forward migration in the chain rather than as an operator one-off.
--
-- NOT dropped here, deliberately:
--   * public.appointment_records -- RUNBOOK.md:128 "Do not drop `public.appointment_records` until every
--     runtime reference is gone"; R7_TABLE_DISPOSITION.md:126-150 records live bidirectional traffic
--     (pgAppointmentProjection.ts, pgDoctorAppointments.ts, publicAppointmentRecordSync.ts, the admin
--     soft-delete route) and rules "KEEP for now, ARCHIVE+DROP deferred". Its ARCHIVE is now scripted;
--     its DROP stays unauthored until those readers/writers are gone.
--   * integrator.rubitime_records / integrator.rubitime_events / rubitime_api_throttle /
--     rubitime_booking_profiles / rubitime_branches / rubitime_services / rubitime_cooperators --
--     already dropped by the landed integrator migration
--     apps/integrator/src/integrations/rubitime/db/migrations/20260724_0002_drop_r7_raw_tables.sql
--     (R7_TABLE_DISPOSITION.md:79-105). Not re-dropped here; not duplicated.
--   * KEEP-list (RUNBOOK.md:31-38): public.patient_bookings, public.be_external_entity_mappings,
--     integrator.booking_calendar_map, integrator.message_retry_jobs, and the public.booking_* catalog
--     tables (blocked on Track C R3-CATALOG). None of them is named below.
--
-- SAFETY: `IF EXISTS` makes it idempotent and a clean no-op on an already-clean database. `CASCADE`
-- matches the landed integrator R7 drop migration; no table outside this pair references either mirror
-- (the pair has no inbound FKs -- the canonical replacements are `be_*`/`patient_bookings`), so CASCADE
-- cannot reach a KEEP-list table. Rollback is by archive restore per the runbook's rollback contract
-- (DB_CLEANUP_SEQUENCE.md §Step 7), not by a down-migration.
--
-- Custom SQL migration: no drizzle snapshot, same convention as 0206..0236.
DROP TABLE IF EXISTS public.rubitime_records CASCADE;
--> statement-breakpoint
DROP TABLE IF EXISTS public.rubitime_events CASCADE;
