-- 0246: drop be_specialist_service_availability.duration_minutes_override.
--
-- Authority: owner ruling, taskdb #1023 -- "service duration is configured once by the admin in
-- the service catalogue; giving different specialists different services is solved by the
-- specialist<->service binding itself, NOT by a second duration field." A per-specialist duration
-- override is unnecessary complexity and a second source of truth for the same fact.
--
-- VERIFIED SAFE TO DROP (2026-07-26, on the TEST database): be_specialist_service_availability had
-- 12 rows, ZERO with a non-null duration_minutes_override. No data is lost.
--
-- NO WRITER: the one admin screen that creates these bindings
-- (apps/webapp/src/app/app/settings/BookingEngineSection.tsx, POST
-- /api/admin/booking-engine/availability kind:"specialist_service") never sent this field; that
-- screen is currently unmounted (nothing imports it) and is untouched by this migration.
--
-- NO REMAINING READER: both call sites that resolved duration via
-- `ssa.durationMinutesOverride ?? service.durationMinutes`
-- (src/infra/repos/pgBookingScheduling.ts resolveCanonicalAvailabilityContext,
-- src/infra/repos/pgBookingCalendar.ts resolveSchedulingForSlots) now read `service.durationMinutes`
-- directly, landing in the same commit as this migration. The Drizzle column definition
-- (db/schema/bookingEngine.ts), the zod input schema and write path
-- (src/app/api/admin/booking-engine/availability/route.ts), the port/type contracts
-- (src/modules/booking-engine/{ports,types}.ts) and every write site in
-- src/infra/repos/pgBookingEngine.ts are updated in the same commit set. After this migration,
-- `grep -rn "durationMinutesOverride|duration_minutes_override" apps/webapp/src apps/webapp/db`
-- is empty except this file and the original creation migration
-- (0086_booking_engine_canonical.sql, left as historical record per this repo's "do not hand-edit
-- existing migrations" convention).
--
-- NO INDEX TO DROP: the column was never indexed (see db-migrations-hot-column-indexes.mdc --
-- this rule is about adding indexes on hot columns, not relevant to a drop) and carried no CHECK
-- constraint.
--
-- SAFETY: `IF EXISTS` makes this idempotent and a no-op if re-applied or run against a database
-- that never had the column. No down-migration; rollback is by re-adding the (now dead) column,
-- which would restore no data since every current row is NULL in it.
--
-- Custom SQL migration: no drizzle snapshot, same convention as 0206..0245.
ALTER TABLE public.be_specialist_service_availability
  DROP COLUMN IF EXISTS duration_minutes_override;
