import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requirePatientApiBusinessAccess } from '@/app-layer/guards/requireRole';
import { isNativePushProvider } from '@/modules/web-push/nativePush';
import { buildAppDeps } from '@/app-layer/di/buildAppDeps';
const registration = z.object({ installationId: z.string().min(8).max(512), token: z.string().min(8).max(8192), provider: z.enum(['rustore', 'fcm', 'hms']) });
function service() { const targetService = buildAppDeps().nativePushTargets; if (!targetService) throw new Error('native_push_unavailable'); return targetService; }
async function runtimeProjectId() { const row = await buildAppDeps().systemSettings.getSetting('rustore_universal_push_therapygo', 'admin'); const value = row?.valueJson; if (!value || typeof value !== 'object' || Array.isArray(value)) return null; const envelope = (value as { value?: unknown }).value; return envelope && typeof envelope === 'object' && !Array.isArray(envelope) && typeof (envelope as { projectId?: unknown }).projectId === 'string' ? (envelope as { projectId: string }).projectId : null; }
/** Patient route fixes Therapy Go; the client cannot select a surface. */
export async function GET() { const gate = await requirePatientApiBusinessAccess(); if (!gate.ok) return gate.response; const projectId = await runtimeProjectId(); return NextResponse.json({ ok: true, ...(await service().status(gate.session.user.userId, 'therapygo')), ...(projectId ? { projectId } : { projectId: null, runtime: 'unavailable' }) }); }
export async function POST(request: Request) { const gate = await requirePatientApiBusinessAccess(); if (!gate.ok) return gate.response; const parsed = registration.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ ok: false, error: 'invalid_body' }, { status: 400 }); try { await service().register({ userId: gate.session.user.userId, appId: 'therapygo', ...parsed.data }); } catch (error) { if (error instanceof Error && error.message === 'native_push_installation_conflict') return NextResponse.json({ ok: false, error: 'installation_conflict' }, { status: 409 }); throw error; } return NextResponse.json({ ok: true }); }
export async function DELETE(request: Request) { const gate = await requirePatientApiBusinessAccess(); if (!gate.ok) return gate.response; const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body || typeof body.installationId !== 'string' || !isNativePushProvider(body.provider)) return NextResponse.json({ ok: false, error: 'invalid_body' }, { status: 400 }); await service().revoke(gate.session.user.userId, 'therapygo', body.provider, body.installationId); return NextResponse.json({ ok: true }); }
