'use client';

import { useEffect, useState, useTransition } from 'react';
import { Button } from '@/shared/ui/doctor/primitives/button';

type Summary = { prepaymentQuote: { amountMinor: number; currency: string } | null; payment: { amountMinor: number; status: string } | null };
type Response = { summary?: Summary; error?: string; totalMinor?: number | null; manualPaidMinor?: number };
const money = (amountMinor: number, currency = 'RUB') => (amountMinor / 100).toLocaleString('ru-RU', { style: 'currency', currency });
function errorLabel(error: string) { if (error === 'payments_disabled') return 'Приём платежей выключен для клиники.'; if (error === 'payment_provider_unavailable' || error === 'payment_link_unavailable') return 'Платёжный провайдер не настроен.'; if (error === 'appointment_amount_unavailable') return 'Стоимость записи не определена.'; if (error === 'already_paid') return 'Запись уже оплачена.'; return 'Не удалось выполнить действие.'; }

export function AppointmentPaymentSection({ apiBase, appointmentId }: { apiBase: string; appointmentId: string }) {
  const [summary, setSummary] = useState<Summary | null>(null); const [totalMinor, setTotalMinor] = useState<number | null>(null); const [manualPaidMinor, setManualPaidMinor] = useState(0); const [error, setError] = useState<string | null>(null); const [link, setLink] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const load = async () => { const response = await fetch(`${apiBase}/appointments/${encodeURIComponent(appointmentId)}/payment`); const json = await response.json() as Response; if (!response.ok || !json.summary) throw new Error(json.error ?? 'not_found'); setSummary(json.summary); setTotalMinor(json.totalMinor ?? null); setManualPaidMinor(json.manualPaidMinor ?? 0); };
  useEffect(() => { void load().catch((cause: unknown) => setError(cause instanceof Error ? cause.message : 'not_found')); }, [appointmentId]);
  const run = (action: 'cash' | 'link') => startTransition(async () => { setError(null); try { const response = await fetch(`${apiBase}/appointments/${encodeURIComponent(appointmentId)}/payment`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action }) }); const json = await response.json() as { ok?: boolean; error?: string; paymentLink?: string }; if (!response.ok || !json.ok) throw new Error(json.error ?? 'request_failed'); if (json.paymentLink) setLink(json.paymentLink); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'request_failed'); } });
  const captured = summary?.payment?.status === 'succeeded' ? summary.payment.amountMinor : 0; const paid = captured + manualPaidMinor; const quote = summary?.prepaymentQuote?.amountMinor ?? null;
  return <section className="space-y-2 border-t border-border pt-3 text-sm" aria-label="Оплата записи">{totalMinor && paid >= totalMinor ? <p className="font-medium">Оплачено: {money(paid)}</p> : paid > 0 && totalMinor ? <p>Частично оплачено: {money(paid)} из {money(totalMinor)} · осталось {money(totalMinor - paid)}</p> : quote ? <p>Не оплачено · предоплата {money(quote, summary?.prepaymentQuote?.currency)}</p> : <p>Не оплачено</p>}{error ? <p className="text-destructive" role="alert">{errorLabel(error)}</p> : null}<div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="outline" disabled={pending || !totalMinor || paid >= totalMinor} onClick={() => run('cash')}>Оплачено наличными</Button><Button type="button" size="sm" disabled={pending || !totalMinor || paid >= totalMinor} onClick={() => run('link')}>Выставить счёт</Button></div>{link ? <div className="flex items-start gap-3"><a className="break-all text-primary underline" href={link} target="_blank" rel="noreferrer">{link}</a><img width="144" height="144" alt="QR-код платёжной ссылки" src={`https://quickchart.io/qr?size=144&text=${encodeURIComponent(link)}`} /></div> : null}</section>;
}
