name: Host Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no 
          ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 
          "/opt/projects/bersoncarebot/deploy/host/deploy-prod.sh"